Repository DefactoSoftware/website, pull requests merged in 2018-12, with the labels that each got.

#1637 Remove link to Uprise Festival from posts
  source/blog/de/2017-11-09-uprise-dublin-2017.html.markdown
  source/blog/nl/2017-11-03-uprise-dublin-2017.html.markdown
Labels: ready, 🇩🇪 defactolearning.de, 🇳🇱 defacto.nl

#1636 Prevent Rubocop being run against ERB files
  .rubocop.yml
Labels: ready, 🌐 global

#1635 Fix next case nav on lower resolution
  source/stylesheets/posts/_page-controls.scss
Labels: ready, 🇩🇪 defactolearning.de, 🇳🇱 defacto.nl

#1623 Remove former employee from About Us page
  data/team.yml
  source/images/team/susan-apfel.jpg
Labels: ready, 🌐 global

#1631 Add ARIA landmarks
  source/cases/_case-sidebar.html.erb
  source/layouts/post_layout.erb
  source/localizable/footer/_footer.erb
  source/localizable/zoeken.html.erb
  source/stylesheets/layout/_footer.scss
Labels: ready, 🌐 global

#1618 Update background-position for post headers
  source/stylesheets/posts/_post-header.scss
Labels: ready, 🌐 global

#1629 Update CAPP Agile Learning product hero
  source/localizable/capp-agile-learning.html.erb
  source/localizable/capp-agile-learning/_clients.erb
  source/localizable/capp-agile-learning/_content.de.erb
  source/localizable/capp-agile-learning/_content.en.erb
  source/localizable/capp-agile-learning/_content.nl.erb
  source/localizable/capp-agile-learning/_hero.erb
  source/localizable/capp-agile-learning/_testimonials.erb
  source/localizable/capp-agile-learning/_why.erb
  source/localizable/header/_header.erb
  source/stylesheets/pages/_capp-agile-learning.scss
Labels: ready, 🌐 global

#1641 Add Pohl Boskamp blog to website
  data/news_nl.yml
  source/blog/nl/2018-11-22-elliott-masies-learning-2018.html.markdown
  source/blog/nl/2018-12-04-audit-pohl-boskamp.html.markdown
  source/images/blog/featured/20181204-audit-featured.jpg
  source/images/blog/social/audit-social-1200x630.jpg
  source/images/moods/audit-mood.jpg
  source/images/news/news-audit.jpg
  source/images/news/news-klantendag.jpg
Labels: copy, ready, 🇳🇱 defacto.nl

#1644 Fix post header padding
  source/stylesheets/posts/_post-header.scss
Labels: ready, 🌐 global

#1646 Update blog text
  source/blog/nl/2018-12-04-audit-pohl-boskamp.html.markdown
Labels: ready, 🇳🇱 defacto.nl

#1648 Prevent other locales from building
  config.rb
  source/layouts/redirect.erb
Labels: ready, 🌐 global

#1647 Align product-icon svg
  source/stylesheets/layout/_header.scss
Labels: ready

#1649 Update featured news with Learntec 2019
  data/news_de.yml
  data/news_nl.yml
  source/images/news/learntec-news.jpg
  source/images/news/oeb-news.jpg
Labels: ready, 🇩🇪 defactolearning.de, 🇳🇱 defacto.nl

#1652 Support page
  locales/de.yml
  locales/nl.yml
  source/localizable/footer/_footer-nav.de.erb
  source/localizable/header/_nav-dropdowns.erb
  source/localizable/header/_nav-mobile.erb
  source/localizable/support.html.erb
  source/localizable/support/support.de.md.erb
  source/localizable/support/support.nl.md.erb
Labels: ready, 🇩🇪 defactolearning.de

#1651 Update text and header of Implementierungen page
  locales/de.yml
  source/localizable/implementaties/_implementaties.de.md.erb
Labels: ready, 🇩🇪 defactolearning.de

#1654 Use underscore for support partials
  source/localizable/support/_support.de.md.erb
  source/localizable/support/_support.nl.md.erb
Labels: ready, 🇩🇪 defactolearning.de, 🇳🇱 defacto.nl

#1639 Remove header-image div
  source/localizable/capp-agile-learning.html.erb
  source/localizable/capp-lms.html.erb
  source/localizable/header/_header.erb
  source/localizable/index.html.erb
  source/stylesheets/layout/_header.scss
  source/stylesheets/pages/_capp-agile-learning.scss
  source/stylesheets/pages/_capp-lms-new.scss
  source/stylesheets/pages/_home.scss
Labels: ready, 🌐 global

#1653 Remove prevent building of other langs
  config.rb
Labels: ready, 🌐 global

#1656 Update button text to fit better
  locales/nl.yml
Labels: ready, 🇳🇱 defacto.nl

#1657 Add event workshop Innovative Lernumgebung
  data/news_de.yml
  helpers/page_classes.rb
  source/images/news/kundentag-news.jpg
  source/images/news/workshop-innovative-lernumgebung-news.png
  source/images/social/workshop-09042019-1200x630.png
  source/localizable/evenementenagenda/_events.de.md.erb
  source/localizable/evenementenagenda/workshop-innovative-lernumgebung.html.erb
Labels: ready, 🇩🇪 defactolearning.de

#1655 Make every regular build for production so it removes other locales
  Rakefile
Labels: ready, 🌐 global

#1660 Update blog title, url and add redirect
  data/news_nl.yml
  data/redirects_nl.yml
  source/blog/nl/2018-12-04-audit-farmaceutisch-bedrijf-pohl-boskamp.html.markdown
Labels: ready, 🇳🇱 defacto.nl

#1661 Add supportteam job to job page
  source/jobs/nl/supportteam-medewerker.html.markdown.erb
Labels: ready, 🇳🇱 defacto.nl

#1662 Add and feature audit blog
  data/news_de.yml
  source/blog/de/2018-11-22-kundentag-november-2018.html.markdown
  source/blog/de/2018-12-21-audit-pharmaunternehmen-pohl-boskamp.html.markdown
Labels: ready, 🇩🇪 defactolearning.de
