Repository DefactoSoftware/website, pull requests merged in 2018-11, with the labels that each got.

#1526 Add customizing intercom launcher blog
  source/blog/en/2018-10-31-customizing-the-intercom-launcher.html.markdown
  source/blog/nl/2018-10-31-customizing-the-intercom-launcher.html.markdown
  source/images/blog/featured/20181031-customizing-the-intercom-launcher.png
  source/images/blog/new-vs-old-launcher.png
  source/images/blog/social/customizing-the-intercom-launcher-1200x630.png
  source/images/moods/art.jpg
Labels: post, ready, 🇬🇧 en.defacto.nl, 🇳🇱 defacto.nl

#1536 Set auto ids to true for markdown
  config.rb
Labels: ready, 🌐 all sites

#1530 Update some formatting in old posts
  source/blog/nl/2017-02-22-met-e-learning-toekomst-vormgeven.html.markdown
  source/blog/nl/2017-06-20-wij-zijn-iso-gecertificeerd.html.markdown
  source/blog/nl/2017-06-27-defacto-30-jaar.html.markdown
  source/blog/nl/2017-07-14-ken-je-potentie-kenniswerker.html.markdown
  source/blog/nl/2017-07-18-de-geschiedenis-van-onze-stadsvilla.html.markdown
  source/blog/nl/2017-08-07-micro-toekomst.html.markdown
  source/blog/nl/2017-08-24-leiderschap-succes-of-ondergang.html.markdown
  source/blog/nl/2017-08-28-kennisoverdracht-realiseren.html.markdown
  source/blog/nl/2017-09-04-zerocopter-veilige-software-door-ethical-hackers.html.markdown
  source/blog/nl/2017-09-12-blockchain-in-education.html.markdown
  source/blog/nl/2017-09-21-verslag-elixirconf-us-2017.html.markdown
  source/blog/nl/2017-09-25-van-learningspaces-naar-capp-agile.html.markdown
  source/blog/nl/2017-10-02-combineer-kennis-met-games.html.markdown
  source/blog/nl/2017-10-04-terugblik-defacto-gebruikersoverleg-najaar-2017.html.markdown
  source/blog/nl/2017-10-16-sociaal-cognitieve-leertheorie.html.markdown
  source/blog/nl/2017-10-23-masie-over-masie-learning-2017.html.markdown
  source/blog/nl/2017-10-26-consultant-bastiaan-barelds.html.markdown
  source/blog/nl/2017-11-03-uprise-dublin-2017.html.markdown
  source/blog/nl/2017-11-23-masie-de-drie-belangrijkste-takeaways-uit-orlando.html.markdown
  source/blog/nl/2017-11-28-rivm-wint-award-beste-corporate-academy.html.markdown
  source/blog/nl/2017-12-04-defacto-werkt-niet-samen-met-mediation-agency.html.markdown
  source/blog/nl/2018-01-17-5-moments-of-need.html.markdown
  source/blog/nl/2018-04-19-sneakpreview-nieuwe-versie-capp-lms.html.markdown
Labels: ready, 🇳🇱 defacto.nl

#1531 Update some more formatting in old posts
  source/blog/nl/2013-04-10-zelf-e-learning-maken.html.markdown
  source/blog/nl/2015-09-24-laat-de-babyboomers-in-elk-geval-hun-kennis-inleveren.html.markdown
  source/blog/nl/2015-10-07-conversie-van-historische-LMS-data-naar-capp-probleemloos.html.markdown
  source/blog/nl/2015-11-13-verslag-defacto-gebruikersbijeenkomst.html.markdown
  source/blog/nl/2015-12-04-koppelingen-met-hrm-systemen-zijn-helemaal-niet-ingewikkeld.html.markdown
  source/blog/nl/2015-12-14-innovatie-die-wat-oplevert.html.markdown
  source/blog/nl/2016-01-04-aantoonbaar-bekwaam-in-het-kader-van-convenant-medische-technologie.html.markdown
  source/blog/nl/2016-01-08-the-future-is-now.html.markdown
  source/blog/nl/2016-02-01-snelkookpanimplementatie-gemeente-den-haag-twee-weken-uit-en-thuis.html.markdown
  source/blog/nl/2016-02-08-van-controleren-naar-faciliteren.html.markdown
  source/blog/nl/2016-02-19-eerste-defacto-gebruikersoverleg-2016.html.markdown
  source/blog/nl/2016-02-22-nieuwe-privacywet.html.markdown
  source/blog/nl/2016-03-17-nieuw-geleerd-nieuw-gedaan.html.markdown
  source/blog/nl/2016-04-14-zelfsturende-teams-hot-topic-in-de-zorg.html.markdown
  source/blog/nl/2016-04-25-zelfsturende-teams-ondersteunen-met-kwaliteitspaspoort.html.markdown
  source/blog/nl/2016-06-20-SCORM-sores-eenvoudig-stappenplan-probleemanalyse.html.markdown
  source/blog/nl/2016-06-30-zorg-dat-leren-voor-je-werkt.html.markdown
  source/blog/nl/2016-07-05-bevoegd-niet-bekwaam-waar-bekwaamheid-over-gaat.html.markdown
  source/blog/nl/2016-07-12-bedrijfsuitje-defacto-2016.html.markdown
  source/blog/nl/2016-07-15-samenwerking-op-basis-van-co-creatie-en-duurzaamheid.html.markdown
  source/blog/nl/2016-07-18-alweer-een-systeem.html.markdown
  source/blog/nl/2016-07-21-talent-management-met-capp.html.markdown
  source/blog/nl/2016-07-26-verbeterd-kwaliteitspaspoort-door-samenwerking.html.markdown
  source/blog/nl/2016-10-05-gebruikersoverleg-22-september-2016.html.markdown
  source/blog/nl/2016-11-28-capp-agile-learning-op-websummit.html.markdown
Labels: ready, 🇳🇱 defacto.nl

#1540 Predate dev blogs
  source/blog/nl/2017-04-22-flexible-cover-images-using-intrinsic-ratio.html.markdown
  source/blog/nl/2017-10-24-color-placeholders-for-loading-images.html.markdown
Labels: ready, 🇳🇱 defacto.nl

#1535 Restructure and refactor Helpers
  config.rb
  data/team.yml
  helpers/content.rb
  helpers/language_switcher.rb
  helpers/links.rb
  helpers/locale.rb
  helpers/meta.rb
  helpers/navigation.rb
  helpers/page.rb
  helpers/page_classes.rb
  helpers/posts.rb
  helpers/style.rb
  source/jobs/index.html.erb
  source/localizable/header/_main-nav.de.erb
  source/localizable/header/_main-nav.en.erb
  source/localizable/header/_main-nav.nl.erb
  source/localizable/partials/_social-share.erb
Labels: ready, 🌐 all sites

#1533 Add a comment about the pen image
  config.rb
Labels: ready, 🇬🇧 en.defacto.nl, 🇳🇱 defacto.nl

#1554 Update NL featured newsitems with Bremen blog
  data/news_nl.yml
  source/images/news/arnoud-bremen.jpg
  source/images/news/gebruikersbijeenkomst.png
Labels: post, ready, 🇳🇱 defacto.nl

#1553 Let crawlers access staging
  source/robots.txt.erb
Labels: ready, 🌐 all sites

#1557 Update user number to 250.000 for EN homepage
  locales/en.yml
Labels: copy, ready, 🇬🇧 en.defacto.nl

#1559 Add events to eventpage
  source/localizable/evenementenagenda/_events.nl.md.erb
Labels: post, ready, 🇳🇱 defacto.nl

#1567 Remove browser version inject in forms
  source/javascripts/_forms.js.erb
Labels: ready, 🌐 all sites

#1563 Update readme thanks
  README.md
Labels: ready, 🌐 all sites

#1568 Remove maps js + abc
  source/javascripts/_map.js
  source/javascripts/all.js.erb
Labels: ready, 🌐 all sites

#1569 Clean some svgs
  source/images/arrow.svg
  source/images/capp-12-intro-bg.svg
  source/images/icons/icon-contact.svg
  source/images/icons/icon-demo.svg
  source/images/icons/icon-support.svg
  source/images/logos/360feedback.png
  source/images/logos/360feedback.svg
  source/images/logos/capp-agile-alt.svg
  source/images/logos/capp-agile.svg
  source/images/logos/capp-new-version-white.svg
  source/images/logos/capp-new-version.svg
  source/images/moods/home.svg
  source/stylesheets/pages/_contact.scss
  source/stylesheets/pages/_home.scss
Labels: ready, 🌐 all sites

#1571 Update nav_link_to helper for new navigation
  helpers/navigation.rb
  source/stylesheets/layout/_dropdown-menu.scss
  source/stylesheets/layout/_header.scss
Labels: ready, 🌐 all sites

#1573 Rename a few scss files
  source/stylesheets/pages/_360-feedback.scss
  source/stylesheets/pages/_capp-agile-learning.scss
  source/stylesheets/pages/_klanten.scss
  source/stylesheets/pages/_kwaliteitspaspoort.scss
Labels: ready, 🌐 all sites

#1494 Add jobs section with a job
  config.rb
  locales/en.yml
  source/jobs/_jobs-text.en.md.erb
  source/jobs/en/elixir-developer.html.markdown
  source/jobs/index.html.erb
  source/layouts/post_layout.erb
  source/localizable/footer/_footer-nav.en.erb
  source/localizable/header/_main-nav.en.erb
  source/localizable/open-source.html.erb
Labels: ready, 🇬🇧 en.defacto.nl

#1562 Use what-input to style :focus
  Gemfile
  Gemfile.lock
  source/javascripts/all.js.erb
  source/stylesheets/base/_form-elements.scss
  source/stylesheets/base/_typography.scss
Labels: ready, 🌐 all sites

#1577 Use capital for Jobs
  locales/en.yml
Labels: ready, 🇬🇧 en.defacto.nl

#1575 Add inline svg
  helpers/images.rb
  source/images/logos/logo-defacto.svg
  source/localizable/header/_header.erb
  source/localizable/header/_logo.erb
Labels: ready, 🌐 all sites

#1579 Add display block to the article-preview link around image
  source/stylesheets/posts/_blog-article-preview.scss
Labels: ready, 🌐 all sites

#1578 Highlight parents in navigation for posts
  .rubocop.yml
  helpers/navigation.rb
Labels: ready, 🌐 all sites

#1583 Add heading to social share section
  source/localizable/partials/_social-share.erb
  source/stylesheets/sections/_social-share.scss
Labels: ready, 🌐 all sites

#1585 Update CAPP Agile link and QR code to Zorgdemo
  source/images/screenshots/capp-agile-qr-code-nl.png
  source/images/screenshots/capp-agile-qr-code_nl.png
  source/localizable/capp-agile/_content.nl.erb
Labels: ready, 🇳🇱 defacto.nl

#1580 Add Klantendag blog and update news items
  data/news_nl.yml
  source/blog/nl/2018-11-14-defacto-klantendag-november-2018.html.markdown
  source/images/blog/featured/20181114-klantendag.jpg
  source/images/blog/klantendag-005.jpg
  source/images/blog/klantendag-009.jpg
  source/images/blog/klantendag-012.jpg
  source/images/blog/social/social-klantendag-1200x630.jpg
  source/images/moods/mood-klantendag.jpg
  source/images/news/avl.jpg
  source/images/news/news-klantendag.jpg
Labels: copy, ready, 🇳🇱 defacto.nl

#1591 Fix grammatical error and sentence structure
  source/blog/nl/2018-11-14-defacto-klantendag-november-2018.html.markdown
  source/images/blog/klantendag-005.jpg
  source/images/blog/klantendag-009.jpg
  source/images/blog/klantendag-012.jpg
  source/images/moods/klantendag-mood.jpg
  source/images/moods/mood-klantendag.jpg
  source/images/news/news-klantendag.jpg
Labels: copy, ready, 🇳🇱 defacto.nl

#1586 Update capp agile learning logo filenames
  locales/de.yml
  locales/en.yml
  locales/nl.yml
  source/images/logos/capp-agile-white.png
  source/images/logos/logo-capp-agile-learning.svg
  source/localizable/capp-agile/_hero.erb
  source/localizable/producten/_producten.de.md.erb
  source/localizable/producten/_producten.en.md.erb
  source/localizable/producten/_producten.nl.md.erb
  source/stylesheets/pages/_capp-agile-learning.scss
  source/stylesheets/pages/_producten.scss
Labels: ready, 🌐 all sites

#1587 Use SVG for language flags
  helpers/language_switcher.rb
  source/images/flags/de.png
  source/images/flags/de.svg
  source/images/flags/en.png
  source/images/flags/en.svg
  source/images/flags/nl.png
  source/images/flags/nl.svg
Labels: ready, 🌐 all sites

#1592 Remove past Defacto event from eventpages
  source/localizable/evenementenagenda/_events.de.md.erb
  source/localizable/evenementenagenda/_events.nl.md.erb
Labels: ready, 🇩🇪 defactolearning.de, 🇳🇱 defacto.nl

#1595 Sitemap prio
  source/localizable/index.html.erb
  source/sitemap.xml.builder
Labels: ready, 🌐 all sites

#1596 Use a helper for ~related~ other posts
  helpers/posts.rb
  source/localizable/partials/_related-posts.erb
  source/stylesheets/posts/_other-posts.scss
Labels: ready, 🌐 all sites

#1602 Improve text and add product links
  source/blog/nl/2018-11-14-defacto-klantendag-november-2018.html.markdown
Labels: copy, ready, 🇳🇱 defacto.nl

#1603 Feature OEB event on homepages
  data/news_de.yml
  data/news_nl.yml
  source/images/news/arnoud-bremen.jpg
  source/images/news/cme-news.jpg
  source/images/news/oeb-news.jpg
Labels: post, ready, 🇩🇪 defactolearning.de, 🇳🇱 defacto.nl

#1574 Update solution icons
  source/images/icons/borging-turquoise.png
  source/images/icons/capp-pink.png
  source/images/icons/compliance-turquoise.svg
  source/images/icons/developing-blue.svg
  source/images/icons/informal-green.svg
  source/images/icons/informeel-green.png
  source/images/icons/learning-blue.svg
  source/images/icons/learning-pink.svg
  source/images/icons/leren-blue.png
  source/images/icons/ontwikkelen-blue.png
  source/localizable/home/_solutions.erb
Labels: ready, 🌐 all sites

#1582 Remove events.ga
  source/javascripts/_events.ga.js
  source/javascripts/all.js.erb
  source/jobs/_apply-button.erb
  source/localizable/360-feedback.html.erb
  source/localizable/70-20-10.html.erb
  source/localizable/call-to-actions/_360-feedback.erb
  source/localizable/capp-agile/_hero.erb
  source/localizable/capp-lms-new/_page-nav.erb
  source/localizable/contact/_contact.md.erb
  source/localizable/digital-hospital.html.erb
  source/localizable/footer/_footer.erb
  source/localizable/home/_hero.erb
  source/localizable/home/_news.erb
  source/localizable/partials/_social-share.erb
Labels: ready, 🌐 all sites

#1606 Re-add e-learning starterkit
  source/localizable/producten/_producten.de.md.erb
Labels: ready, 🇩🇪 defactolearning.de

#1584 Add heading to clients section
  locales/de.yml
  locales/en.yml
  locales/nl.yml
  source/localizable/clients/_clients-section.de.md.erb
  source/localizable/clients/_clients-section.en.md.erb
  source/localizable/clients/_clients-section.nl.md.erb
  source/stylesheets/sections/_clients-section.scss
Labels: ready, 🌐 all sites

#1605 Update product index(es)
  source/images/logos/logo-360feedback.svg
  source/images/logos/logo-capp-agile-learning-white-vertical.svg
  source/images/logos/logo-capp-lms-white.svg
  source/images/logos/logo-kwaliteitsmonitor-white-vertical.svg
  source/images/logos/logo-kwaliteitspaspoort-white-vertical.svg
  source/images/logos/logo-qualitatspass-white-horizontal.svg
  source/images/logos/logo-qualityportfolio-white-vertical.svg
  source/localizable/producten/_producten.de.md.erb
  source/localizable/producten/_producten.en.md.erb
  source/localizable/producten/_producten.nl.md.erb
  source/stylesheets/pages/_producten.scss
Labels: ready, 🌐 all sites

#1614 Use higher timeout for external links
  source/blog/en/2015-05-20-animated-loading-indicator-with-isometric-cubes.html.markdown
  test.rb
Labels: ready, 🌐 global

#1609 Add Kundentag blog to website
  data/news_de.yml
  source/blog/de/2018-10-15-cme-punkte-schnell-erfassen-mit-capp-lms.html.markdown
  source/blog/de/2018-11-22-kundentag-november-2018.html.markdown
  source/images/blog/featured/20181122-kundentag.jpg
  source/images/blog/kundentag-drieluik-01.jpg
  source/images/blog/kundentag-drieluik-02.jpg
  source/images/blog/kundentag-drieluik-03.jpg
  source/images/blog/kundentag-drieluik.jpg
  source/images/blog/social/kundentag-social-1200x630.jpg
  source/images/moods/kundentag-mood.jpg
  source/images/news/kundentag-news.jpg
  source/images/news/mfa.jpg
Labels: copy, ready, 🇩🇪 defactolearning.de

#1613 Clean up config.rb
  config.rb
Labels: ready, 🌐 global

#1615 Add and feature Learning 2018 blog
  data/news_nl.yml
  source/blog/nl/2018-11-14-defacto-klantendag-november-2018.html.markdown
  source/blog/nl/2018-11-22-elliott-masies-learning-2018.html.markdown
  source/images/blog/featured/20181123-masies-learning.jpg
  source/images/blog/masies-01.jpg
  source/images/blog/masies-02.jpg
  source/images/blog/masies-03.jpg
  source/images/blog/masies-04.jpg
  source/images/blog/social/masies-learning-1200x630.jpg
  source/images/moods/masies-learning-mood.jpg
  source/images/news/masies-news.jpg
Labels: copy, ready, 🇳🇱 defacto.nl

#1626 Add noreferrer to some external links
  source/cases/_case-sidebar.html.erb
  source/jobs/_apply-button.erb
  source/localizable/partials/_social-share.erb
Labels: ready, 🌐 global

#1627 Update blog formats
  source/blog/de/2015-07-03-nur-zufriedener-kunde-ein-guter-kunde.html.markdown
  source/blog/de/2015-07-13-kleinen-unterschiede-zwischen-deutschland-niederlanden.html.markdown
  source/blog/de/2016-06-23-Hauptstadt-Kongress-Berlin-2016.html.markdown
  source/blog/de/2016-07-15-e-learning-freiheit.html.markdown
  source/blog/de/2016-07-21-SCORM-Sores-ein-einfach-auszufuehrender-plan.html.markdown
  source/blog/de/2016-08-03-drei-grunde-warum-interkollegiales-testen-aufmerksamkeit-bekommen-sollte.html.markdown
  source/blog/de/2016-09-15-SIE-haben-den-qualitatspass-verbessert.html.markdown
  source/blog/de/2016-10-04-capp-talentmanagement-im-gesundheitswesen.html.markdown
  source/blog/de/2016-10-25-qualitat-sichern-durch-bildungsmanagement.html.markdown
  source/blog/de/2016-11-03-schon-wieder-ein-neues-system.html.markdown
  source/blog/de/2016-12-05-warum-unsere-geschichte-so-wichtig-ist.html.markdown
  source/blog/de/2017-01-10-lernen-ist-arbeit-ist-lernen.html.markdown
  source/blog/de/2017-01-25-neuer-kunde-klinikum-itzehoe.html.markdown
  source/blog/de/2017-02-06-potentiale-heben-innovationen-leben.html.markdown
  source/blog/de/2017-02-21-workshop-e-learning-zukunftsthemen.html.markdown
  source/blog/de/2017-03-08-fachkraftemangel-im-gesundheitswesen-agieren-statt-reagieren.html.markdown
  source/blog/de/2017-04-03-pflegetag-2017.html.markdown
  source/blog/de/2017-05-09-von-krankenschwester-zur-softwareexpertin.html.markdown
  source/blog/de/2017-05-22-klinikmanagementpersonal-2017.html.markdown
  source/blog/de/2017-06-06-pulslos-leben.html.markdown
  source/blog/de/2017-06-19-wir-sind-iso-zertifiziert.html.markdown
  source/blog/de/2017-07-05-defacto-gibt-es-seit-30-jahren.html.markdown
  source/blog/de/2017-07-31-nutzen-sie-ihr-potenzial.html.markdown
  source/blog/de/2017-08-10-mikrolernen.html.markdown
  source/blog/de/2017-08-14-social-learning-in-der-mittagspause.html.markdown
  source/blog/de/2017-08-24-mitarbeiterfuhrung-alles-oder-nichts.html.markdown
  source/blog/de/2017-08-28-wissensvermittlung-in-die-tat-umsetzen.html.markdown
  source/blog/de/2017-09-06-durch-ethische-hacker-an-sicherheit-gewinnen.html.markdown
  source/blog/de/2017-09-15-blockchain-in-der-Bildungskonferenz-2017.html.markdown
  source/blog/de/2017-09-18-bundestagswahl-2017.html.markdown
  source/blog/de/2017-09-21-besuch-der-elixirconf-2017-in-der-USA.html.markdown
  source/blog/de/2017-09-25-learningspaces-wird-zu-capp-agile-learning.html.markdown
  source/blog/de/2017-10-02-bieten-sie-wissen-und-spiele.html.markdown
  source/blog/de/2017-10-09-teamwork-wird-es-neu-definiert.html.markdown
  source/blog/de/2017-10-16-sozialkognitive-lerntheorie-heute.html.markdown
  source/blog/de/2017-10-23-wissensdatenbank-die-loesung-fuer-modernes-wissensmanagement-im-gesundheitswesen.html.markdown
  source/blog/de/2017-11-09-uprise-dublin-2017.html.markdown
  source/blog/de/2017-11-23-learning-2017-drei-wichtigsten-erkenntnisse.html.markdown
  source/blog/de/2017-12-01-compliance-und-sicherheit-im-krankenhaus-safety-first.html.markdown
  source/blog/de/2018-01-03-defacto-jahresruckblick-2017.html.markdown
  source/blog/de/2018-01-16-studie-zur-patientenzufriedenheit.html.markdown
  source/blog/de/2018-02-14-digitales-lernen-und-entwickeln-von-a-bis-z.html.markdown
  source/blog/de/2018-03-05-five-moments-of-need-lernen-im-richtigen-bedarfsmoment.html.markdown
  source/blog/de/2018-04-30-neuer-kunde-medius-kliniken.html.markdown
  source/blog/de/2018-06-14-medizinischer-fachangestellter-im-krankenhaus-entlastung-fur-den-arzt.html.markdown
  source/blog/de/2018-07-09-fort-und-weiterbildung-fur-medizinische-fachangestellte-gute-perspektiven.html.markdown
  source/blog/nl/2016-04-25-zelfsturende-teams-ondersteunen-met-kwaliteitspaspoort.html.markdown
  source/blog/nl/2017-09-04-zerocopter-veilige-software-door-ethical-hackers.html.markdown
Labels: ready, 🇩🇪 defactolearning.de, 🇳🇱 defacto.nl

#1628 Update blog formats
  data/redirects_en.yml
  source/blog/en/2015-05-20-animated-loading-indicator-with-isometric-cubes.html.markdown
  source/blog/en/2015-05-21-give-them-knowledge-and-games.html.markdown
  source/blog/en/2015-09-04-lost-and-found-generation-z.html.markdown
  source/blog/en/2015-09-25-learning-in-the-age-of-tutorial.html.markdown
  source/blog/en/2015-10-08-attributes-of-a-leader.html.markdown
  source/blog/en/2015-10-30-intergenerational-knowledge-transfer.html.markdown
  source/blog/en/2016-02-08-today-and-social-learning-theory.html.markdown
  source/blog/en/2016-03-16-teamwork-is-it-redefined.html.markdown
  source/blog/en/2016-03-30-lunch-break-learning.html.markdown
  source/blog/en/2016-04-11-questions-and-answers.html.markdown
  source/blog/en/2016-05-17-micro-future.html.markdown
  source/blog/en/2016-05-30-making-capp-agile-learning-fit-the-ipad.html.markdown
  source/blog/en/2016-06-12-focus-your-teams-ability-to-scale-knowledge.html.markdown
  source/blog/en/2016-10-16-ending-the-lms-era-for-organisations.html.markdown
  source/blog/en/2017-01-04-customizing-the-intercom-launcher.html.markdown
  source/blog/en/2017-04-30-wrong-estimation-or-opinion-formation-largest-internet-company-by-2030.html.markdown
  source/blog/en/2017-06-30-using-your-potential-knowledge-employee-is-what-makes-a-company.html.markdown
  source/blog/en/2017-07-11-defacto-30-years.html.markdown
  source/blog/en/2017-09-04-zerocopter-ethical-hacking-and-security-through-hackers.html.markdown
  source/blog/en/2017-09-21-visiting-elixirconf-us-2017.html.markdown
  source/blog/en/2017-09-25-learningspaces-to-capp-agile.html.markdown
Labels: ready, 🇬🇧 en.defacto.nl
