Repository DefactoSoftware/website, pull requests merged in 2018-02, with the labels that each got.

#1077 Add featured testimonial(s) to clients page
  locales/de.yml
  source/localizable/index.html.erb
  source/localizable/klanten.html.erb
  source/localizable/partials/_featured-testimonial.erb
Labels: ready

#1076 Update main nav
  locales/nl.yml
  source/localizable/header/_main-nav.de.erb
  source/localizable/header/_main-nav.en.erb
  source/localizable/header/_main-nav.nl.erb
  source/localizable/over-ons.html.erb
  source/localizable/over-ons/_sidebar.erb
  source/stylesheets/_header.scss
Labels: ready

#1072 Upload blog lernen und entwickeln von a bis z
  source/blog/de/2018-01-16-studie-zur-patientenzufriedenheit.html.markdown
  source/blog/de/2018-02-14-digitales-lernen-und-entwickeln-von-a-bis-z.html.markdown
  source/images/blog/featured/20180209-digitales-lernen-und-entwickeln-a-z.jpg
  source/images/blog/social/digitales-lernen-und-entwickeln-a-z-1200x630.jpg
Labels: ready

#1081 Update team feb 2018
  data/team.yml
  source/images/team/femke-santema.jpg
Labels: ready

#1080 Remove sentence about elixirconf
  source/jobs/nl/_over-ons.md
Labels: ready

#1079 Update Front End vacancy copy
  source/jobs/nl/front-end-developer.html.markdown.erb
Labels: ready

#1082 Update Nokogiri to 1.8.x
  Gemfile.lock
Labels: ready

#1083 Remove great David from website - but not before tomorrow
  data/team.yml
  source/images/team/david-fritsch.jpg
Labels: ready

#1086 Remove event from DE homepage
  source/images/events/logo-zeq.png
  source/localizable/home/_events.erb
  source/localizable/index.html.erb
  source/stylesheets/components/_base.scss
  source/stylesheets/components/_events.scss
Labels: ready

#1070 Privacy policy (NL)
  locales/de.yml
  locales/nl.yml
  source/localizable/partials/_footer.erb
  source/localizable/privacy-policy.html.erb
  source/localizable/privacy-policy/_privacy-policy.de.md.erb
  source/localizable/privacy-policy/_privacy-policy.nl.md.erb
Labels: ready

#1085 Change Luchtvaartcollege to Luchtvaart Community
  data/clients_de.yml
  data/clients_en.yml
  data/clients_nl.yml
  source/images/references/luchtvaart-community-schiphol.png
  source/images/references/luchtvaartcollege-schiphol.png
Labels: ready

#1078 Update hover on main nav
  source/stylesheets/_header.scss
  source/stylesheets/components/_dropdown-menu.scss
Labels: ready

#1087 Remove sentence from german jobs
  source/jobs/de/business-developer.html.markdown
  source/jobs/de/consultant.html.markdown
  source/jobs/de/mitarbeiter-im-marketing.html.markdown
  source/jobs/de/software-developer.html.markdown
Labels: ready

#1090 Update organization schema and remove publisher google plus link
  source/layouts/layout.erb
  source/localizable/partials/_organization_schema.erb
Labels: ready

#1089 Remove media folder
  source/localizable/media/_media.de.md.erb
  source/localizable/media/_media.en.md.erb
  source/localizable/media/_media.nl.md.erb
Labels: ready

#1088 Remove video tracking scripts
  source/javascripts/_vimeo.ga.js
  source/javascripts/_youtube.ga.js
  source/javascripts/all.js.erb
  source/localizable/elearning/_elearning.nl.md.erb
Labels: ready

#1091 Remove unused appointment stuff
  source/javascripts/_home.js
  source/javascripts/all.js.erb
  source/stylesheets/components/_base.scss
  source/stylesheets/components/_cta-appointment.scss
Labels: ready

#1092 Use a section for social share buttons
  source/layouts/blog_post_layout.erb
  source/layouts/cases_post_layout.erb
  source/layouts/jobs_post_layout.erb
  source/localizable/partials/_social-share.erb
  source/stylesheets/_cases.scss
  source/stylesheets/components/_social-share.scss
Labels: ready

#1093 Cases page control
  locales/nl.yml
  source/layouts/cases_post_layout.erb
  source/stylesheets/components/_base.scss
  source/stylesheets/components/_page-controls.scss
Labels: ready, wait

#1097 Close marketing job
  source/jobs/nl/marketeer.html.markdown.erb
Labels: ready

#1099 Remove hiring jobs badge
  source/localizable/footer/_footer-nav.de.erb
  source/localizable/footer/_footer-nav.nl.erb
  source/stylesheets/_footer.scss
Labels: ready

#1098 Add TUV Certificate again
  source/images/footer/iso-9001-14001.png
  source/localizable/partials/_footer.erb
Labels: ready

#1096 Remove 503 hipchat link and another one
  source/blog/nl/2016-03-17-nieuw-geleerd-nieuw-gedaan.html.markdown
Labels: ready

#1095 Case Strukton and some other things
  locales/nl.yml
  source/cases/nl/strukton.html.markdown.erb
  source/cases/nl/zinn.html.markdown.erb
  source/images/cases/strukton/logo-white.png
  source/images/cases/strukton/logo.png
  source/images/cases/strukton/mood.jpg
  source/localizable/clients/_clients-cases-overview.erb
  source/localizable/klanten.html.erb
  source/stylesheets/_cases.scss
Labels: wip
