Repository DefactoSoftware/website, pull requests merged in 2018-10, with the labels that each got.

#1342 Update events index
  locales/de.yml
  locales/nl.yml
  source/images/calendar-background.svg
  source/localizable/evenementenagenda.html.erb
  source/localizable/evenementenagenda/_events.de.md.erb
  source/localizable/evenementenagenda/_events.nl.md.erb
  source/stylesheets/_evenementenagenda.scss
Labels: ready

#1344 Remove workshop 🇩🇪
  config.rb
  data/news_de.yml
  source/images/events/LMU.png
  source/images/events/campusG.png
  source/images/news/mfa.jpg
  source/images/news/workshop-innovative-lernumgebung.png
  source/images/social/workshop-18102018-1200x630.png
  source/localizable/evenementenagenda/_events.de.md.erb
  source/localizable/evenementenagenda/workshop-innovative-lernumgebung.html.erb
  source/stylesheets/_evenementenagenda.scss
Labels: ready

#1345 Add and feature Seminar page in new event design
  data/news_nl.yml
  source/images/news/seminar-november-2018-orange.png
  source/images/news/umcg.jpg
  source/localizable/evenementenagenda/_events.nl.md.erb
  source/localizable/evenementenagenda/seminar-november-2018.html.erb
  source/stylesheets/_evenementenagenda.scss
Labels: ready

#1343 Update event index details
  source/images/calendar-background.svg
  source/localizable/evenementenagenda/_events.de.md.erb
  source/localizable/evenementenagenda/_events.nl.md.erb
  source/stylesheets/_evenementenagenda.scss
Labels: ready

#1348 Uniformed use of timestamps in hero and main text
  source/localizable/evenementenagenda/gebruikersbijeenkomst-november-2018.html.erb
Labels: ready

#1349 Use formkeep_id or fallback to urls.contact
  locales/de.yml
  locales/nl.yml
  source/localizable/call-to-actions/_register-event.erb
  source/localizable/evenementenagenda/gebruikersbijeenkomst-november-2018.html.erb
Labels: ready

#1352 Use user-select:none on main nav
  source/stylesheets/_header.scss
Labels: ready

#1378 Add Kunden Event
  source/localizable/evenementenagenda/_events.de.md.erb
  source/stylesheets/_evenementenagenda.scss
Labels: ready, 🇩🇪 DE

#1392 Remove raquos
  source/localizable/evenementenagenda/_events.nl.md.erb
Labels: ready

#1393 Fix missing translation for formkeep title for german demo request
  locales/de.yml
Labels: ready, 🇩🇪 de

#1391 Update page_titles
  config.rb
  source/localizable/index.html.erb
Labels: ready

#1396 Fix missing translations English CAPP LMS page
  locales/en.yml
Labels: ready

#1400 Fix missing translation on links on services
  locales/en.yml
Labels: ready, 🇬🇧 en.defacto.nl

#1397 Fix img alt on thanks page
  locales/de.yml
Labels: ready, 🇩🇪 defactolearning.de

#1402 Update link to BMBF site
  source/blog/de/2018-09-27-fordermittel-fur-digitale-medien-in-der-beruflichen-bildung-im-gesundheitswesen.html.markdown
Labels: ready, 🇩🇪 defactolearning.de

#1401 Add Clubabend 18 okt
  source/localizable/evenementenagenda/_events.de.md.erb
  source/stylesheets/_evenementenagenda.scss
Labels: ready, 🇩🇪 defactolearning.de

#1350 Add a page about our open source stuffs
  locales/de.yml
  locales/en.yml
  locales/nl.yml
  source/images/moods/code.jpg
  source/images/open-source/celljs.png
  source/images/open-source/elixir.png
  source/images/open-source/hours.png
  source/images/open-source/middleman.png
  source/images/open-source/phoenix.png
  source/images/open-source/pickupgamebot.png
  source/localizable/footer/_footer-nav.de.erb
  source/localizable/footer/_footer-nav.en.erb
  source/localizable/footer/_footer-nav.nl.erb
  source/localizable/header/_main-nav.de.erb
  source/localizable/header/_main-nav.en.erb
  source/localizable/header/_main-nav.nl.erb
  source/localizable/open-source.html.erb
  source/stylesheets/_open-source.scss
  source/stylesheets/base/_buttons.scss
  source/stylesheets/base/_variables.scss
  source/stylesheets/main.scss
Labels: ready, 🇳🇱 defacto.nl

#1414 Remove Hospital
  data/news_nl.yml
Labels: ready

#1409 Change all youtube embeds on blog to no-cookie urls
  source/blog/de/2016-08-03-drei-grunde-warum-interkollegiales-testen-aufmerksamkeit-bekommen-sollte.html.markdown
  source/blog/de/2016-10-25-qualitat-sichern-durch-bildungsmanagement.html.markdown
  source/blog/de/2017-02-06-potentiale-heben-innovationen-leben.html.markdown
  source/blog/de/2017-07-05-defacto-gibt-es-seit-30-jahren.html.markdown
  source/blog/en/2016-10-16-ending-the-lms-era-for-organisations.html.markdown
  source/blog/en/2017-07-11-defacto-30-years.html.markdown
  source/blog/nl/2016-06-30-zorg-dat-leren-voor-je-werkt.html.markdown
  source/blog/nl/2016-07-12-bedrijfsuitje-defacto-2016.html.markdown
  source/blog/nl/2016-10-05-gebruikersoverleg-22-september-2016.html.markdown
  source/blog/nl/2017-07-18-de-geschiedenis-van-onze-stadsvilla.html.markdown
  source/blog/nl/2017-10-26-consultant-bastiaan-barelds.html.markdown
Labels: ready, 🌐 all sites

#1422 Remove ziekenhuis
  data/news_nl.yml
Labels: ready

#1417 Add schema.org markup to Gebruikersbijeenkomst
  source/localizable/evenementenagenda/_schema-gebruikersbijeenkomst-november-2018.erb
  source/localizable/evenementenagenda/gebruikersbijeenkomst-november-2018.nl.html.erb
Labels: ready, 🇳🇱 defacto.nl

#1416 Fix z-index of intercom launcher
  source/stylesheets/components/_base.scss
  source/stylesheets/components/_intercom-launcher.scss
  source/stylesheets/components/_privacy-notification.scss
Labels: ready, 🌐 all sites

#1410 Update posts typography and width
  source/stylesheets/_jobs.scss
  source/stylesheets/_posts.scss
  source/stylesheets/base/_variables.scss
Labels: ready, 🌐 all sites

#1432 Update Twijnstra blog
  source/blog/nl/2015-06-29-capp-agile-learning-een-veilige-ruimte-om-te-leren-van-elkaar.html.markdown
Labels: ready, 🇳🇱 defacto.nl

#1435 Update NL news section with Dianet case
  data/news_nl.yml
  source/images/news/dianet.jpg
  source/images/news/gebruikersbijeenkomst.png
Labels: ready, 🇳🇱 defacto.nl

#1423 Restructure Stylesheets Folder
  source/stylesheets/base/_base.scss
  source/stylesheets/base/_fonts.scss
  source/stylesheets/base/_layout.scss
  source/stylesheets/components/_base.scss
  source/stylesheets/config/_mixins.scss
  source/stylesheets/config/_variables.scss
  source/stylesheets/layout/_dropdown-menu.scss
  source/stylesheets/layout/_footer.scss
  source/stylesheets/layout/_header.scss
  source/stylesheets/main.scss
  source/stylesheets/pages/_360.scss
  source/stylesheets/pages/_70-20-10.scss
  source/stylesheets/pages/_bedankt.scss
  source/stylesheets/pages/_blog.scss
  source/stylesheets/pages/_capp-agile.scss
  source/stylesheets/pages/_capp-lms-new.scss
  source/stylesheets/pages/_capp-lms-old.scss
  source/stylesheets/pages/_cases.scss
  source/stylesheets/pages/_clients.scss
  source/stylesheets/pages/_contact.scss
  source/stylesheets/pages/_convenant.scss
  source/stylesheets/pages/_digital-hospital.scss
  source/stylesheets/pages/_download-productsheet.scss
  source/stylesheets/pages/_elearning-starterkit.scss
  source/stylesheets/pages/_error.scss
  source/stylesheets/pages/_evenementenagenda.scss
  source/stylesheets/pages/_home.scss
  source/stylesheets/pages/_jobs.scss
  source/stylesheets/pages/_kpp.scss
  source/stylesheets/pages/_kwaliteitsmonitor.scss
  source/stylesheets/pages/_open-source.scss
  source/stylesheets/pages/_producten.scss
  source/stylesheets/pages/_request-demo.scss
  source/stylesheets/pages/_search.scss
  source/stylesheets/posts/_blog-article-preview.scss
  source/stylesheets/posts/_blog-meta.scss
  source/stylesheets/posts/_blog-tags.scss
  source/stylesheets/posts/_case-sidebar.scss
  source/stylesheets/posts/_page-controls.scss
  source/stylesheets/posts/_pagination.scss
  source/stylesheets/posts/_posts.scss
  source/stylesheets/posts/_related-posts.scss
  source/stylesheets/sections/_call-to-actions.scss
  source/stylesheets/sections/_clients-section.scss
  source/stylesheets/sections/_contact-info.scss
  source/stylesheets/sections/_feature-list.scss
  source/stylesheets/sections/_news.scss
  source/stylesheets/sections/_privacy-notification.scss
  source/stylesheets/sections/_social-share.scss
  source/stylesheets/sections/_solutions.scss
  source/stylesheets/sections/_team.scss
  source/stylesheets/sections/_testimonials.scss
Labels: ready, 🌐 all sites

#1389 Update Hosting and Security Diensten pagina
  source/localizable/hosting/_hosting.nl.md.erb
Labels: ready, 🇳🇱 defacto.nl

#1436 Use https for Sigfox link in internet of things blog
  source/blog/de/2017-11-09-uprise-dublin-2017.html.markdown
  source/blog/nl/2017-11-03-uprise-dublin-2017.html.markdown
Labels: ready, 🇩🇪 defactolearning.de, 🇳🇱 defacto.nl

#1433 Add CME blog
  source/blog/de/2018-09-27-fordermittel-fur-digitale-medien-in-der-beruflichen-bildung-im-gesundheitswesen.html.markdown
  source/blog/de/2018-10-15-cme-punkte-schnell-erfassen-mit-capp-lms.html.markdown
  source/images/blog/featured/20181015-cme.jpg
  source/images/blog/social/cme-1200x630.jpg
  source/images/moods/cme-mood.jpg
  source/localizable/call-to-actions/_appointment-cme.erb
Labels: ready, 🇩🇪 defactolearning.de

#1412 Add Stormruiter blog
  source/blog/nl/2018-10-09-bedrijfsuitje-de-stormruiter.html.markdown
  source/images/blog/featured/20181010-stormruiter-blog.jpg
  source/images/blog/social/stormruiter-1200x630.jpg
  source/images/moods/stormruiter.jpg
Labels: ready, 🇳🇱 defacto.nl

#1445 Update Schnittstelle text with Bundesarztekammer information
  source/localizable/koppelingen/_koppelingen.de.md.erb
Labels: ready, 🇩🇪 defactolearning.de

#1446 Add badges to readme.md
  README.md
Labels: ready, 🌐 all sites

#1448 Feature CME blog and remove unused BFMF image
  data/news_de.yml
  source/images/news/BMBF-news-blog.jpg
  source/images/news/cme-news.jpg
Labels: ready, 🇩🇪 defactolearning.de

#1451 Fix Relationship blog intro
  source/blog/nl/2015-07-03-de-r-van-relatie.html.markdown
Labels: ready, 🇳🇱 defacto.nl

#1452 Make intro bold of NL vs DE blog
  source/blog/nl/2015-07-13-de-vele-kleine-verschillen-tussen-duitsland-en-nederland.html.markdown
Labels: ready, 🇳🇱 defacto.nl

#1453 Fix formatting Glenn's UX blog post
  source/blog/nl/2015-08-12-redesigning-capp.html.markdown
Labels: ready, 🇳🇱 defacto.nl

#1454 Make blog intro of co-makership blog bold
  source/blog/nl/2015-09-02-co-makership-voor-een-optimale-productontwikkeling.html.markdown
Labels: ready, 🇳🇱 defacto.nl

#1456 Remove seminar
  data/news_nl.yml
  source/images/news/gebruikersbijeenkomst.png
  source/images/news/seminar-november-2018-orange.png
  source/images/social/seminar-22112018-1200x630.png
  source/localizable/evenementenagenda/_events.nl.md.erb
  source/localizable/evenementenagenda/seminar-november-2018.nl.html.erb
Labels: ready, 🇳🇱 defacto.nl

#1455 Make the intro of the third umc blog bold
  source/blog/nl/2015-09-11-onze-derde-umc-klant.html.markdown
Labels: ready, 🇳🇱 defacto.nl

#1444 Use 1 post layout
  config.rb
  source/cases/de/doppio-espresso.html.markdown
  source/cases/de/evangelisches-krankenhaus-oldenburg.html.markdown
  source/cases/de/fek-neumunster.html.markdown
  source/cases/de/mumc.html.markdown
  source/cases/de/strukton.html.markdown
  source/cases/de/zinn.html.markdown
  source/cases/nl/antoni-van-leeuwenhoek.html.markdown
  source/cases/nl/dianet.html.markdown
  source/cases/nl/doppio-espresso.html.markdown
  source/cases/nl/mumc.html.markdown
  source/cases/nl/strukton.html.markdown
  source/cases/nl/zinn.html.markdown
  source/jobs/_apply-button.erb
  source/layouts/blog_post_layout.erb
  source/layouts/cases_post_layout.erb
  source/layouts/jobs_post_layout.erb
  source/layouts/post_layout.erb
  source/localizable/clients/_clients-cases-overview.erb
  source/localizable/partials/_related-posts.erb
Labels: ready, 🌐 all sites

#1442 Add proper templating to tags index page
  source/blog/tags.html.erb
  source/stylesheets/pages/_blog.scss
Labels: ready, 🌐 all sites

#1443 Update post (header)
  source/stylesheets/posts/_blog.scss
  source/stylesheets/posts/_cases.scss
  source/stylesheets/posts/_jobs.scss
  source/stylesheets/posts/_post-header.scss
Labels: ready, 🌐 all sites

#1457 Limit to 5 related posts
  source/localizable/partials/_related-posts.erb
Labels: ready, 🌐 all sites

#1450 Fix blog 3 reasons formatting
  source/blog/nl/2016-01-22-drie-redenen-om-meer-intercollegiaal-te-toetsen.html.markdown
Labels: ready, 🇳🇱 defacto.nl

#1420 Add social proof section
  source/localizable/index.html.erb
  source/localizable/partials/_social-proof.erb
  source/localizable/social-proof/_social-proof.nl.html.erb
  source/stylesheets/components/_social-proof.scss
Labels: ready, 🇳🇱 defacto.nl

#1460 A Year Blog: Make the intro bold and add a link to CAPP-LMS
  source/blog/nl/2017-12-22-jaaroverzicht-2017.html.markdown
Labels: ready, 🇳🇱 defacto.nl

#1462 Teamwork blog: Make the intro bold and fix formatting
  source/blog/nl/2017-10-09-teamwork-opnieuw-gedefinieerd.html.markdown
Labels: ready, 🇳🇱 defacto.nl

#1461 New Version Blog: Make the intro bold and add a link to CAPP-LMS
  source/blog/nl/2017-12-18-defacto-presenteert-nieuwe-capp-versie.html.markdown
Labels: ready, 🇳🇱 defacto.nl

#1467 Update DE Kundenveranstaltung text
  source/localizable/evenementenagenda/_events.de.md.erb
Labels: copy, ready, 🇩🇪 defactolearning.de

#1449 Use a less cookie option for vimeo
  source/blog/nl/2016-01-22-drie-redenen-om-meer-intercollegiaal-te-toetsen.html.markdown
  source/blog/nl/2017-11-23-masie-de-drie-belangrijkste-takeaways-uit-orlando.html.markdown
  source/localizable/elearning/_elearning.nl.md.erb
Labels: ready, 🌐 all sites

#1471 Add OEB event to DE Calender page
  source/localizable/evenementenagenda/_events.de.md.erb
Labels: copy, ready, 🇩🇪 defactolearning.de

#1474 Fix links to kpp in cases content
  source/cases/nl/antoni-van-leeuwenhoek.html.markdown
  source/cases/nl/dianet.html.markdown
Labels: ready, 🇳🇱 defacto.nl

#1473 Fix structure of cases-overview - clients
  locales/de.yml
  locales/nl.yml
  source/localizable/clients/_clients-cases-overview.erb
  source/localizable/klanten.html.erb
Labels: ready, 🌐 all sites

#1479 Fix klanten
  source/localizable/klanten.html.erb
Labels: ready, 🌐 all sites

#1483 Add intercom_stats to open source page
  source/images/open-source/intercom.png
  source/localizable/open-source.html.erb
Labels: ready, 🌐 all sites

#1484 Add Learntec Event to DE eventpage
  source/localizable/evenementenagenda/_events.de.md.erb
Labels: copy, ready, 🇩🇪 defactolearning.de

#1481 Fix error uninitialized constant for MissingTranslation
  config.rb
  source/localizable/producten.html.erb
Labels: ready, 🌐 all sites

#1488 Remove Clubabend from DE eventpage
  source/localizable/evenementenagenda/_events.de.md.erb
Labels: copy, ready, 🇩🇪 defactolearning.de

#1486 Add Phoenix label to intercom_stats
  source/localizable/open-source.html.erb
Labels: ready, 🌐 all sites

#1476 Align sidebar-quote with the rest of the content
  source/stylesheets/posts/_case-sidebar.scss
Labels: ready, 🌐 all sites

#1475 Add filled h1 to cases
  source/cases/de/doppio-espresso.html.markdown
  source/cases/de/evangelisches-krankenhaus-oldenburg.html.markdown
  source/cases/de/fek-neumunster.html.markdown
  source/cases/de/mumc.html.markdown
  source/cases/de/strukton.html.markdown
  source/cases/de/zinn.html.markdown
  source/cases/nl/antoni-van-leeuwenhoek.html.markdown
  source/cases/nl/dianet.html.markdown
  source/cases/nl/doppio-espresso.html.markdown
  source/cases/nl/mumc.html.markdown
  source/cases/nl/strukton.html.markdown
  source/cases/nl/zinn.html.markdown
  source/layouts/post_layout.erb
  source/stylesheets/posts/_cases.scss
  source/stylesheets/posts/_post-header.scss
  source/stylesheets/posts/_posts.scss
Labels: ready, 🇩🇪 defactolearning.de, 🇳🇱 defacto.nl

#1492 Use / at the end of internal links to capp-agile-learning
  source/blog/en/2015-05-21-give-them-knowledge-and-games.html.markdown
  source/blog/en/2016-04-11-questions-and-answers.html.markdown
  source/blog/en/2016-10-16-ending-the-lms-era-for-organisations.html.markdown
Labels: ready, 🇬🇧 en.defacto.nl

#1489 Add Flexible cover images using intrinsic ratio post
  config.rb
  source/blog/en/2018-10-22-flexible-cover-images-using-intrinsic-ratio.html.markdown
  source/blog/nl/2018-10-22-flexible-cover-images-using-intrinsic-ratio.html.markdown
  source/images/blog/flexible-cover-images-using-intrinsic-ratio/aspect-ratio-demo.png
  source/images/blog/flexible-cover-images-using-intrinsic-ratio/aspect-ratio.png
  source/images/blog/flexible-cover-images-using-intrinsic-ratio/featured.png
  source/images/blog/flexible-cover-images-using-intrinsic-ratio/header.png
  source/images/blog/flexible-cover-images-using-intrinsic-ratio/intrinsic-ratio-1200x630.png
Labels: post, ready, 🇬🇧 en.defacto.nl, 🇳🇱 defacto.nl

#1499 Fix blog image paths
  source/blog/en/2018-10-22-flexible-cover-images-using-intrinsic-ratio.html.markdown
  source/blog/nl/2018-10-22-flexible-cover-images-using-intrinsic-ratio.html.markdown
Labels: ready

#1500 Fix post avatar
  source/stylesheets/posts/_post-header.scss
Labels: ready, 🇩🇪 defactolearning.de, 🇳🇱 defacto.nl

#1464 Fix 404 home link on deeper 404 pages
  config.rb
  source/localizable/header/_main-nav.de.erb
  source/localizable/header/_main-nav.en.erb
  source/localizable/header/_main-nav.nl.erb
  source/localizable/partials/_header.erb
Labels: ready, 🌐 all sites

#1503 Use link_to instead of nav_link_to for links
  source/cases/_case-sidebar.html.erb
  source/localizable/call-to-actions/_demo-request.erb
  source/localizable/clients/_clients-cases-overview.erb
  source/localizable/contact/_contact.md.erb
  source/localizable/home/_hero.erb
  source/localizable/partials/_featured-testimonial.erb
Labels: ready, 🌐 all sites

#1493 Add event call-to-action
  source/blog/nl/2018-04-19-sneakpreview-nieuwe-versie-capp-lms.html.markdown
  source/localizable/call-to-actions/_information-event.erb
  source/stylesheets/sections/_call-to-actions.scss
Labels: in progress, 🇳🇱 defacto.nl

#1502 Add Clubabend Bremen blog
  source/blog/nl/2018-10-23-netwerkbijeenkomst-clubabend-bremen.html.markdown
  source/images/blog/clubabend-arnoud-chart.png
  source/images/blog/clubabend-blog-bremen.jpg
  source/images/blog/featured/20181023-clubabend-bremen-arnoud.jpg
  source/images/blog/social/clubabend-bremen-1200x630.jpg
  source/images/moods/clubabend-bremen-arnoud-mood.jpg
Labels: post, ready, 🇳🇱 defacto.nl

#1516 Fix image link in network meeting blog
  source/blog/nl/2018-10-23-netwerkbijeenkomst-clubabend-bremen.html.markdown
Labels: ready, 🇳🇱 defacto.nl

#1505 Remove alt from anchors in cases-overview
  source/localizable/clients/_clients-cases-overview.erb
Labels: ready, 🌐 all sites

#1506 Use data-rel instead of rel
  source/javascripts/_privacy-notification.js
  source/localizable/partials/_privacy-notification.erb
Labels: ready, 🌐 all sites

#1513 Fix assets for 'Flexible Cover Images' blog
  source/blog/en/2017-09-25-learningspaces-to-capp-agile.html.markdown
  source/blog/en/2018-10-22-flexible-cover-images-using-intrinsic-ratio.html.markdown
  source/blog/nl/2018-10-22-flexible-cover-images-using-intrinsic-ratio.html.markdown
  source/images/blog/aspect-ratio.png
  source/images/blog/featured/20181022-flexible-cover-images.png
  source/images/blog/social/flexible-cover-images-1200x630.png
  source/images/moods/flexible-cover-images.png
Labels: ready, 🇬🇧 en.defacto.nl, 🇳🇱 defacto.nl

#1507 Remove useless anchor and link to #id instead
  source/localizable/contact.html.erb
Labels: ready, 🌐 all sites

#1509 Fix templates blog and jobs indexes
  source/blog/index.html.erb
  source/jobs/index.html.erb
  source/stylesheets/posts/_jobs.scss
Labels: ready, 🌐 all sites

#1517 Make intro bold of social learning blog
  source/blog/nl/2017-08-14-sociaal-leren-tijdens-de-lunchpauze.html.markdown
Labels: post, ready, 🇳🇱 defacto.nl

#1520 Move partials to designated folders
  source/layouts/layout.erb
  source/localizable/footer/_footer.erb
  source/localizable/header/_header.erb
  source/localizable/header/_logo.erb
  source/localizable/partials/meta/_google_analytics.erb
  source/localizable/partials/meta/_open_graph.erb
  source/localizable/partials/meta/_organization_schema.erb
Labels: ready, 🌐 all sites

#1478 Add a page about Service & Support
  helpers/intercom.rb
  locales/nl.yml
  source/images/moods/support.jpg
  source/layouts/layout.erb
  source/localizable/contact.html.erb
  source/localizable/footer/_footer-nav.nl.erb
  source/localizable/header/_main-nav.nl.erb
  source/localizable/support.html.erb
  source/stylesheets/pages/_support.scss
Labels: ready, 🇳🇱 defacto.nl

#1504 Use https for caniuse.com links
  source/blog/nl/2015-05-20-animated-loading-indicator-with-isometric-cubes.html.markdown
Labels: ready, 🇳🇱 defacto.nl

#1459 Add Color Placeholders for Loading Images blog
  source/blog/en/2018-10-24-color-placeholders-for-loading-images.html.markdown
  source/blog/nl/2018-10-24-color-placeholders-for-loading-images.html.markdown
  source/images/blog/capp-agile-space-tile-loading.gif
  source/images/blog/dominant-colors.png
  source/images/blog/en/dominant-colors.png
  source/images/blog/featured/20181024-color-placeholders.png
  source/images/blog/social/color-placeholders-for-loading-images-1200x630.jpg
  source/images/moods/plate.jpg
Labels: post, ready, 🇬🇧 en.defacto.nl, 🇳🇱 defacto.nl
