Repository DefactoSoftware/website, pull requests merged in 2019-11, with the labels that each got.

#2046 Add blog article about Open Courses
  data/downloads.yml
  locales/nl.yml
  source/blog/nl/2019-11-01-defacto-introduceert-open-courses-extern-cursusaanbod.html.markdown
  source/images/blog/featured/20191101-zinn-open-courses.jpg
  source/images/blog/social/zinn-open-courses-1200x862.jpg
  source/images/blog/zinn-open-courses.jpg
  source/images/moods/zinn-open-courses-mood.jpg
  source/localizable/call-to-actions/_download-open-courses-productsheet.erb
  source/pdf/Productsheet-Open-Courses.pdf
  source/stylesheets/posts/_posts.scss
Labels: ready, 🇳🇱 defacto.nl

#2047 Fix some bad aligned call-to-actions
  source/localizable/70-20-10.html.erb
  source/localizable/convenant-medische-technologie.html.erb
  source/localizable/digital-hospital.html.erb
  source/localizable/e-learning-in-healthcare.html.erb
  source/localizable/implementaties.html.erb
  source/localizable/upgrade.html.erb
  source/stylesheets/pages/_upgrade.scss
Labels: ready, 🇳🇱 defacto.nl

#2048 Add new blog about new live customers
  locales/nl.yml
  source/blog/nl/2019-11-04-capp-lms-twee-grote-ziekenhuizen-live.html.markdown
  source/images/blog/featured/20191104-mumc-spaarne-live.jpg
  source/images/blog/social/mumc-spaarne-live-capp-lms-1200x688.jpg
  source/localizable/call-to-actions/_contact.erb
Labels: 🇳🇱 defacto.nl

#2049 Add blog article about Learning 2019
  locales/nl.yml
  source/blog/nl/2019-11-08-elliot-masie-learning-2019-data-AI-curation.html.markdown
  source/images/blog/cullen-ux-evaluaties.jpg
  source/images/blog/featured/20191108-learning-2019-arnoud.jpg
  source/images/blog/masie-learning-shifts-2020.jpg
  source/images/blog/mosher-trends-werkplekleren.jpg
  source/images/blog/social/learning-2019-arnoud-1200x800.jpg
  source/images/blog/taylor-enquete-learning-2019.jpg
  source/images/moods/learning-2019-mood.jpg
  source/localizable/call-to-actions/_capp-lms-trends.erb
Labels: ready, 🇳🇱 defacto.nl

#2052 Replace existing news items on homepage
  data/news_nl.yml
  source/images/news/learning-2019-news.jpg
  source/images/news/mumc-spaarne-news.jpg
  source/images/news/open-courses-news.jpg
Labels: ready, 🇳🇱 defacto.nl

#2054 Add new blog 'van SCORM naar microleren'
  locales/nl.yml
  source/blog/nl/2019-11-12-van-scorm-module-naar-microleren.html.markdown
  source/images/blog/featured/20191112-scorm-microleren.jpg
  source/images/blog/social/scorm-microleren-1200x688.jpg
  source/localizable/call-to-actions/_contact-microleren.erb
Labels: 🇳🇱 defacto.nl

#2055 Change blog introduction
  source/blog/nl/2019-11-04-capp-lms-twee-grote-ziekenhuizen-live.html.markdown
Labels: ready, 🇳🇱 defacto.nl

#2056 Fix mistyped names
  source/blog/nl/2019-11-08-elliot-masie-learning-2019-data-AI-curation.html.markdown
Labels: ready, 🇳🇱 defacto.nl

#2051 Replace old testimonials on Compliance product page
  data/capp-compliance-testimonials.yml
  source/images/testimonials/hanke-mensink.jpg
  source/images/testimonials/torben-sura.jpg
Labels: ready, 🇳🇱 defacto.nl

#2058 Fix html-proofer ampersand error
  source/blog/nl/2016-04-25-zelfsturende-teams-ondersteunen-met-kwaliteitspaspoort.html.markdown
  source/blog/nl/2016-07-05-bevoegd-niet-bekwaam-waar-bekwaamheid-over-gaat.html.markdown
  source/blog/nl/2016-07-18-alweer-een-systeem.html.markdown
  source/blog/nl/2017-10-09-teamwork-opnieuw-gedefinieerd.html.markdown
  source/blog/nl/2017-11-23-masie-de-drie-belangrijkste-takeaways-uit-orlando.html.markdown
  source/blog/nl/2017-11-28-rivm-wint-award-beste-corporate-academy.html.markdown
  source/blog/nl/2018-01-17-5-moments-of-need.html.markdown
  source/blog/nl/2018-10-31-customizing-the-intercom-launcher.html.markdown
  source/blog/nl/2018-11-22-elliott-masies-learning-2018.html.markdown
  source/blog/nl/2018-12-04-audit-farmaceutisch-bedrijf-pohl-boskamp.html.markdown
  source/blog/nl/2019-11-08-elliot-masie-learning-2019-data-AI-curation.html.markdown
Labels: optimization, ready, 🇳🇱 defacto.nl
