Repository DefactoSoftware/website, pull requests merged in 2019-05, with the labels that each got.

#1832 Update demo request page
  locales/de.yml
  locales/en.yml
  locales/nl.yml
  source/localizable/demo-aanvragen/_content.nl.md.erb
  source/localizable/demo-aanvragen/_hero.erb
Labels: ready, 🌐 all sites

#1835 Make services title (H1) shorter
  locales/nl.yml
Labels: ready, 🇳🇱 defacto.nl

#1833 Update CAPP Agile product page
  locales/nl.yml
  source/localizable/capp-agile-learning/_hero.erb
  source/stylesheets/pages/_capp-agile-learning.scss
Labels: ready, 🇳🇱 defacto.nl

#1836 Remove management assistent job
  source/jobs/nl/management-assistant.html.markdown.erb
Labels: ready, 🇳🇱 defacto.nl

#1838 Add new employee name and image to team
  data/team.yml
  source/images/team/klaus-walheim.jpg
Labels: ready, 🌐 all sites

#1842 Add noindex nofollow to blog tag pages
  source/blog/tag.html.erb
Labels: ready, 🌐 all sites

#1843 Add performance support link to news
  data/news_de.yml
  source/images/news/news-performance-support.jpg
  source/images/news/workshop-innovative-lernumgebung-news.png
Labels: ready, 🇩🇪 defactolearning.de

#1845 Fix short metas
  source/jobs/index.html.erb
  source/localizable/demo-aanvragen.html.erb
Labels: ready, 🇬🇧 en.defacto.nl

#1844 Fix CAPP Agile Learning page things
  source/localizable/capp-agile-learning.html.erb
  source/localizable/capp-agile-learning/_hero.erb
  source/stylesheets/pages/_capp-agile-learning.scss
Labels: ready, 🌐 all sites

#1847 Update blockquote styling
  source/stylesheets/base/_typography.scss
  source/stylesheets/components/_block-quote.scss
Labels: ready

#1846 Add news item for Dianet
  data/news_nl.yml
  source/blog/nl/2019-05-07-defacto-feliciteert-dianet-hkz-certificering-capp-lms.html.markdown
  source/images/blog/featured/20190507-dianet-featured.jpg
  source/images/blog/social/dianet-social-1200x630.jpg
  source/images/moods/dianet-mood.jpg
  source/images/news/dianet-news.jpg
Labels: ready, 🇳🇱 defacto.nl

#1849 Fix typo in blog title
  source/blog/nl/2019-05-07-defacto-feliciteert-dianet-hkz-certificering-capp-lms.html.markdown
Labels: ready, 🇳🇱 defacto.nl

#1850 Set featured from previous blog to false
  source/blog/nl/2019-03-22-huis-voor-de-sport-groningen-coacht-co-met-capp-agile-learning.html.markdown
Labels: ready, 🇳🇱 defacto.nl

#1851 Update team information for May 2019
  data/team.yml
  source/images/team/kira-steffens.jpg
  source/images/team/martha-jorna.jpg
Labels: ready, 🌐 all sites

#1853 Move meta partials outside localizable
  source/layouts/layout.erb
  source/layouts/questionnaire.erb
  source/partials/meta/_google_analytics.erb
  source/partials/meta/_open_graph.erb
  source/partials/meta/_organization_schema.erb
Labels: ready, 🌐 all sites

#1856 Use partial for newsletter signups
  locales/de.yml
  locales/en.yml
  locales/nl.yml
  source/localizable/call-to-actions/_subscribe-newsletter-closed-event.erb
  source/localizable/call-to-actions/_subscribe-newsletter.erb
  source/localizable/footer/_footer.erb
  source/localizable/footer/_newsletter-subscribe-form.erb
  source/partials/_newsletter-signup.erb
Labels: ready, 🌐 all sites

#1841 Put head stuff in a shared partial
  source/javascripts/_navigation.js
  source/layouts/layout.erb
  source/layouts/questionnaire.erb
  source/partials/_head.erb
Labels: ready, 🌐 all sites

#1840 Remove privacy notification from print style
  source/stylesheets/main.scss
  source/stylesheets/sections/_privacy-notification.scss
Labels: ready, 🇳🇱 defacto.nl

#1858 Use background:cover only on screen size medium and up
  source/stylesheets/posts/_post-header.scss
Labels: ready, 🌐 all sites

#1860 Fix DE job posting email address
  source/jobs/de/e-learning-consultant.html.markdown
Labels: ready, 🇩🇪 defactolearning.de

#1859 Change Dutch button captions in home hero
  locales/nl.yml
  source/localizable/home/_hero.erb
Labels: ready, 🇳🇱 defacto.nl

#1862 Fix calc + radial gradients mistakes
  source/stylesheets/components/_hero.scss
  source/stylesheets/config/_mixins.scss
  source/stylesheets/pages/_producten.scss
Labels: ready

#1865 Fix search
  source/layouts/layout.erb
Labels: ready, 🌐 all sites

#1863 Update LMS questionnaire
  data/redirects_nl.yml
  source/images/lms-questions-spider.png
  source/javascripts/questionnaire/questionnaire.min.js
  source/javascripts/questionnaire/questions.js
  source/localizable/home/_hero.erb
  source/localizable/wat-voor-lms-past-bij-mij.html.erb
  source/localizable/wat-voor-lms-past-bij-mij/resultaten.html.erb
  source/stylesheets/questionnaire/_questionnaire.scss
Labels: ready, 🇳🇱 defacto.nl

#1870 Make tag on post optional
  source/layouts/post_layout.erb
Labels: ready, 🌐 all sites

#1866 Remove CNAME.erb
  config.rb
  source/CNAME.erb
Labels: ready, 🌐 all sites

#1871 Use Netlify 301s
  config.rb
  data/redirects_de.yml
  data/redirects_en.yml
  data/redirects_nl.yml
  source/blog/de/2016-09-15-SIE-haben-den-qualitatspass-verbessert.html.markdown
  source/blog/de/2016-10-04-capp-talentmanagement-im-gesundheitswesen.html.markdown
  source/blog/de/2016-10-25-qualitat-sichern-durch-bildungsmanagement.html.markdown
  source/blog/de/2017-01-25-neuer-kunde-klinikum-itzehoe.html.markdown
  source/blog/de/2017-05-09-von-krankenschwester-zur-softwareexpertin.html.markdown
  source/blog/de/2017-12-01-compliance-und-sicherheit-im-krankenhaus-safety-first.html.markdown
  source/blog/de/2018-01-03-defacto-jahresruckblick-2017.html.markdown
  source/blog/de/2018-02-14-digitales-lernen-und-entwickeln-von-a-bis-z.html.markdown
  source/blog/de/2018-04-30-neuer-kunde-medius-kliniken.html.markdown
  source/blog/de/2018-06-14-medizinischer-fachangestellter-im-krankenhaus-entlastung-fur-den-arzt.html.markdown
  source/blog/de/2018-10-15-cme-punkte-schnell-erfassen-mit-capp-lms.html.markdown
  source/cases/de/mumc.html.markdown
  source/cases/de/strukton.html.markdown
  source/cases/de/zinn.html.markdown
  source/localizable/footer/_footer-nav.de.erb
  source/localizable/gezondheidswezen/_introductie.de.md
  source/localizable/themas/_cmt.de.md.erb
Labels: ready, 🌐 all sites

#1861 Add event subscribe page
  locales/de.yml
  locales/en.yml
  locales/nl.yml
  source/javascripts/_forms.js.erb
  source/localizable/bedankt.html.erb
  source/localizable/informatiesessie.html.erb
  source/localizable/informatiesessie/_content.nl.md
  source/partials/_form.erb
  source/partials/_hero.erb
  source/stylesheets/base/_form-elements.scss
  source/stylesheets/components/_forms.scss
  source/stylesheets/components/_hero.scss
Labels: ready, 🇳🇱 defacto.nl

#1872 Add cloudflare to readme
  README.md
Labels: ready, 🌐 all sites

#1857 Add blog about Das Krankenhaus magazine article
  data/news_de.yml
  source/blog/de/2019-03-14-defacto-gewinnt-die-Sana-ag-als-neuen-kunden.html.markdown
  source/blog/de/2019-05-09-mehr-qualitat-in-der-patientenversorgung.html.markdown
  source/images/blog/featured/20190509-fachmagazin-sana.jpg
  source/images/moods/fachmagazin-sana.jpg
  source/images/news/fachmagazin-sana-news.jpg
  source/images/news/sana-news.jpg
  source/images/social/fachmagazin-sana-1200x630.jpg
Labels: ready, 🇩🇪 defactolearning.de

#1873 Update round table signup page
  source/localizable/informatiesessie/_content.nl.md
Labels: ready, 🇳🇱 defacto.nl

#1874 Move blog social image to the right folder
  source/images/blog/social/fachmagazin-sana-1200x630.jpg
Labels: ready, 🇳🇱 defacto.nl

#1869 Update German grammar across the DE website with help of Kira
  locales/de.yml
  source/cases/de/doppio-espresso.html.markdown
  source/cases/de/evangelisches-krankenhaus-oldenburg.html.markdown
  source/cases/de/fek-neumunster.html.markdown
  source/cases/de/strukton.html.markdown
  source/cases/de/zinn.html.markdown
  source/localizable/360-feedback/_360feedback.de.md.erb
  source/localizable/capp-lms-new/_introduction.de.erb
  source/localizable/capp-lms-new/_overview.de.erb
  source/localizable/capp-talent-management/_overview.erb
  source/localizable/gezondheidswezen/_leerplatform.de.html.erb
  source/localizable/kwaliteitspaspoort-new/_introduction.de.erb
  source/localizable/kwaliteitspaspoort-new/_overview.de.erb
  source/localizable/over-ons/_over-ons.de.md.erb
  source/localizable/performance-support/_introductie.de.md
  source/localizable/themas/_70-20-10.de.md.erb
  source/localizable/themas/_digital-hospital.de.md.erb
Labels: ready, 🇩🇪 defactolearning.de

#1880 Add German Events to the eventcalender page
  source/localizable/evenementen/_events.de.md.erb
  source/localizable/evenementenagenda.html.erb
Labels: ready, 🇩🇪 defactolearning.de

#1881 Update introduction text of round table event page
  source/localizable/informatiesessie.html.erb
  source/localizable/informatiesessie/_content.nl.md
Labels: ready, 🇳🇱 defacto.nl

#1868 Add Pohl Boskamp case
  source/cases/de/pohl-boskamp.html.markdown
  source/images/cases/pohl-boskamp/logo-white.png
  source/images/cases/pohl-boskamp/mood.jpg
  source/images/cases/pohl-boskamp/social.jpg
Labels: ready, 🇩🇪 defactolearning.de

#1882 Add conversion page for e-book "Abenteuer Elearning"
  locales/de.yml
  source/images/moods/e-book-abenteuer-e-learning.jpg
  source/localizable/e-book-leren-en-laten-leren.html.erb
  source/partials/_form.erb
  source/partials/_hero.erb
  source/stylesheets/components/_hero.scss
Labels: ready, 🇩🇪 defactolearning.de

#1883 Subscribe to Webinar
  locales/de.yml
  source/images/moods/webinar.jpg
  source/localizable/webinar.html.erb
  source/localizable/webinar/_content.de.md
  source/partials/_form.erb
  source/stylesheets/components/_hero.scss
Labels: ready, 🇩🇪 defactolearning.de

#1885 Use flex 1 1 auto for smaller screens
  source/stylesheets/layout/_footer.scss
Labels: ready, 🌐 all sites

#1887 Add whitepaper 'Performance Support'
  source/pdf/Whitepaper_Performance_Support.pdf
Labels: ready, 🇩🇪 defactolearning.de

#1888 Update webinar
  locales/de.yml
  source/localizable/webinar.html.erb
Labels: ready, 🇩🇪 defactolearning.de

#1884 Add Performance Support conversion page
  locales/de.yml
  source/localizable/performance-support-whitepaper.html.erb
Labels: ready, 🇩🇪 defactolearning.de

#1889 Update the News image of the Fachmagazin blog
  source/images/news/fachmagazin-sana-news.jpg
Labels: ready, 🇩🇪 defactolearning.de
