Repository DefactoSoftware/website, pull requests merged in 2019-08, with the labels that each got.

#1971 Update CAPP Compliance screenshots
  source/images/screenshots/capp-compliance/capp-compliance-certificaatbeheer.png
  source/images/screenshots/capp-compliance/capp-compliance-inzicht-manager.png
  source/images/screenshots/capp-compliance/capp-compliance-kwaliteitspaspoort.png
  source/localizable/capp-compliance/nl/_product-overview.erb
Labels: ready, 🇳🇱 defacto.nl

#1972 Add CAPP Quizzes to Navigations
  data/navigations_nl.yml
  source/images/icons/capp-quizzes.svg
  source/stylesheets/config/_variables.scss
  source/stylesheets/layout/_header.scss
Labels: ready, 🇳🇱 defacto.nl

#1973 Update homepage news items
  data/news_nl.yml
  source/images/news/capp-lms-news.jpg
  source/images/news/curation-news.png
Labels: ready, 🇳🇱 defacto.nl

#1974 Update layout CAPP Quizzes page
  locales/nl.yml
  source/localizable/capp-quizzes.html.erb
  source/localizable/capp-quizzes/_download-productsheet.nl.erb
  source/localizable/capp-quizzes/_product-overview.nl.erb
  source/localizable/quizzes/_content.nl.md
  source/stylesheets/base/_buttons.scss
  source/stylesheets/components/_on-page-navigation.scss
  source/stylesheets/config/_variables.scss
  source/stylesheets/pages/_capp-quizzes.scss
Labels: ready

#1975 Add quizzes to product index
  locales/nl.yml
  source/localizable/producten/_producten.nl.md.erb
  source/stylesheets/pages/_producten.scss
Labels: ready, 🇳🇱 defacto.nl

#1976 Use product layout for compliance api
  data/redirects_nl.yml
  locales/nl.yml
  source/localizable/capp-compliance-api.html.erb
  source/localizable/capp-compliance-api/_applications.nl.erb
  source/localizable/capp-compliance-api/_download-productsheet.erb
  source/localizable/capp-compliance-api/_how-it-works.nl.erb
  source/localizable/capp-compliance-api/_introduction.nl.erb
  source/localizable/capp-compliance-api/_on-page-navigation.erb
  source/localizable/capp-compliance/nl/_product-overview.erb
  source/localizable/compliance-api.html.erb
  source/localizable/compliance-api/_hero.nl.erb
  source/localizable/compliance-api/_how-it-works.nl.erb
  source/stylesheets/base/_buttons.scss
  source/stylesheets/components/_on-page-navigation.scss
  source/stylesheets/config/_variables.scss
  source/stylesheets/pages/_compliance-api.scss
  source/stylesheets/pages/_product-page.scss
Labels: ready, 🇳🇱 defacto.nl

#1978 Add CAPP Compliance API to Navigations
  data/navigations_nl.yml
  source/images/icons/capp-compliance-api.svg
  source/stylesheets/layout/_header.scss
Labels: ready, 🇳🇱 defacto.nl

#1979 Add CAPP Compliance API to Product Index
  locales/nl.yml
  source/localizable/producten.html.erb
  source/localizable/producten/_producten.en.erb
  source/localizable/producten/_producten.md.erb
  source/localizable/producten/_producten.nl.erb
  source/stylesheets/pages/_producten.scss
Labels: ready, 🇳🇱 defacto.nl

#1977 Update CAPP Quizzes to 2019
  locales/nl.yml
  source/images/screenshots/capp-quizzes/capp-quizzes-statistieken.png
  source/images/screenshots/capp-quizzes/capp-quizzes-toets-maken.png
  source/images/screenshots/capp-quizzes/capp-quizzes-wizard.png
  source/localizable/capp-quizzes.html.erb
  source/localizable/capp-quizzes/_introduction.nl.erb
  source/localizable/capp-quizzes/_product-overview.nl.erb
Labels: ready, 🇳🇱 defacto.nl

#1981 Fix key typo
  source/localizable/capp-quizzes.html.erb
Labels: ready, 🇳🇱 defacto.nl

#1980 Move social proof partial and cleanup home
  source/localizable/index.html.erb
  source/localizable/social-proof/_social-proof.nl.html.erb
  source/partials/_social-proof.erb
Labels: ready, 🌐 all sites

#1982 Fix changing file name to something stupid
  source/localizable/producten/_producten.de.erb
Labels: ready, 🌐 all sites

#1965 360: Use partial for hero and add a partial for button blocks
  source/localizable/360-feedback.html.erb
  source/partials/_button.erb
  source/partials/_hero.erb
Labels: ready, 🌐 all sites

#1983 Fix hero image on ios
  source/stylesheets/components/_hero.scss
Labels: ready, 🌐 all sites

#1985 Update social proof
  source/partials/_social-proof.erb
Labels: ready, 🇳🇱 defacto.nl

#1984 Update CAPP LMS page to use product page layout
  locales/nl.yml
  source/images/logos/new/logo-capp-lms.svg
  source/localizable/capp-lms-old/_capp-entwickeln.de.erb
  source/localizable/capp-lms-old/_capp-hero.de.erb
  source/localizable/capp-lms-old/_capp-lms.de.md.erb
  source/localizable/capp-lms.html.erb
  source/localizable/capp-lms/de/_call-to-action.erb
  source/localizable/capp-lms/de/_hero.erb
  source/localizable/capp-lms/de/_introduction.erb
  source/localizable/capp-lms/de/_more.erb
  source/localizable/capp-lms/de/_on-page-navigation.erb
  source/localizable/capp-lms/de/_overview.erb
  source/localizable/capp-lms/en/_content.md.erb
  source/localizable/capp-lms/en/_hero.erb
  source/localizable/capp-lms/nl/_call-to-action.erb
  source/localizable/capp-lms/nl/_introduction.erb
  source/localizable/capp-lms/nl/_product-overview.erb
  source/localizable/producten/_producten.nl.erb
  source/stylesheets/base/_buttons.scss
  source/stylesheets/components/_on-page-navigation.scss
  source/stylesheets/config/_variables.scss
  source/stylesheets/pages/_capp-lms-new.scss
  source/stylesheets/pages/_product-page.scss
Labels: ready, 🇳🇱 defacto.nl

#1986 Use new capp icon everywhere
  data/navigations_nl.yml
  source/images/icons/capp-lms.svg
  source/localizable/home/_solutions.erb
  source/localizable/producten/_producten.nl.erb
  source/stylesheets/layout/_header.scss
  source/stylesheets/pages/_producten.scss
Labels: ready, 🇳🇱 defacto.nl

#1990 Remove qscert links for returning Your connection is not private
  source/partials/footer/_footer.erb
Labels: ready, 🌐 all sites

#1989 Re-add tags for healthcare cases
  locales/de.yml
  source/cases/de/evangelisches-krankenhaus-oldenburg.html.markdown
  source/cases/de/fek-neumunster.html.markdown
  source/localizable/gezondheidswezen.html.erb
Labels: ready, 🇩🇪 defactolearning.de

#1991 Update link to intercom site
  source/blog/en/2017-01-04-customizing-the-intercom-launcher.html.markdown
  source/blog/nl/2018-10-31-customizing-the-intercom-launcher.html.markdown
Labels: ready, 🇳🇱 defacto.nl

#1992 Invert CAPP LMS logo
  source/images/logos/new/logo-capp-lms.svg
Labels: ready, 🇳🇱 defacto.nl

#1987 Use 2 column layout for product navigation group
  source/stylesheets/layout/_header.scss
Labels: ready, 🌐 all sites

#1994 Rename class to item_class
  data/navigations_de.yml
  data/navigations_en.yml
  data/navigations_nl.yml
  source/partials/header/_nav-dropdowns.erb
  source/partials/header/_nav-mobile.erb
Labels: ready, 🌐 all sites

#1998 Fix link to intercom about new messenger
  source/blog/en/2018-10-31-customizing-the-intercom-launcher.html.markdown
Labels: ready, 🇬🇧 en.defacto.nl

#1999 Remove all references to staging
  config.rb
  helpers/links.rb
  helpers/meta.rb
  source/robots.txt.erb
Labels: ready, 🌐 all sites

#2000 Remove home copy styling
  source/stylesheets/pages/_home.scss
Labels: ready, 🇩🇪 defactolearning.de

#2001 Update home hero
  source/localizable/360-feedback.html.erb
  source/localizable/index.html.erb
  source/partials/_button.erb
  source/partials/_hero.erb
  source/stylesheets/components/_hero.scss
  source/stylesheets/pages/_home.scss
  source/stylesheets/pages/_product-page.scss
Labels: ready, 🇳🇱 defacto.nl

#2002 Add some enters in the on page nav locals
  source/localizable/capp-agile-learning.html.erb
  source/localizable/capp-compliance-api.html.erb
  source/localizable/capp-compliance.html.erb
  source/localizable/capp-lms.html.erb
  source/localizable/capp-quizzes.html.erb
Labels: ready, 🇳🇱 defacto.nl

#2003 Update News section
  data/news_de.yml
  data/news_nl.yml
  locales/de.yml
  locales/nl.yml
  source/images/news/curation-news.png
  source/localizable/home/_news.erb
  source/localizable/index.html.erb
  source/partials/_button.erb
  source/partials/_news.erb
  source/stylesheets/base/_buttons.scss
  source/stylesheets/sections/_news.scss
Labels: ready, 🇩🇪 defactolearning.de, 🇳🇱 defacto.nl

#2004 Only use featured blog on English homepage
  source/localizable/index.html.erb
Labels: ready, 🌐 all sites

#2005 Remove stats section from homepage
  source/localizable/index.html.erb
  source/partials/_social-proof.erb
  source/stylesheets/components/_social-proof.scss
Labels: ready, 🇳🇱 defacto.nl

#2006 Add SaaS Whitepaper
  data/downloads.yml
  locales/nl.yml
  source/localizable/hosting-security.html.erb
  source/localizable/hosting/_download-whitepaper.erb
  source/localizable/hosting/_hero.erb
  source/pdf/Whitepaper-SaaS-CAPP.pdf
Labels: ready, 🇳🇱 defacto.nl

#1995 Update event RSVP page for new event
  source/localizable/informatiesessie.html.erb
  source/localizable/informatiesessie/_content.nl.md
Labels: ready, 🇳🇱 defacto.nl

#2008 Remove old events and linked pages from German event calendar
  source/images/moods/webinar.jpg
  source/localizable/evenementen/_events.de.md.erb
  source/localizable/webinar-compliance-und-qualifikationsmanagement-16-07-2019.html.erb
  source/localizable/webinar-compliance-und-qualifikationsmanagement-18-07-2019.html.erb
  source/localizable/webinar-curated-learning-04-07-2019.html.erb
Labels: ready, 🇩🇪 defactolearning.de

#2010 Exclude Normalize.scss from linter
  .scss-lint.yml
Labels: ready, 🌐 all sites

#2011 Add news item for ZPE exhibition
  data/news_de.yml
  source/images/news/news-audit.jpg
  source/images/news/zpe-koeln.jpg
  source/localizable/evenementen/_events.de.md.erb
Labels: ready, 🇩🇪 defactolearning.de

#2013 Remove team member
  data/team.yml
  source/images/team/jeroen-dijkhuis.jpg
  source/localizable/support.html.erb
Labels: ready, 🌐 all sites

#2014 Add Duc to the team
  data/team.yml
  source/images/team/duc-vu.jpg
Labels: ready, 🌐 all sites

#2015 Add RSVP page for key user event
  locales/nl.yml
  source/localizable/key-user-event.html.erb
  source/localizable/key-user-event/_content.nl.md
  source/partials/_form.erb
Labels: ready, 🇳🇱 defacto.nl

#2017 Add tag label to news items
  data/news_de.yml
  data/news_nl.yml
  source/partials/_news.erb
  source/stylesheets/sections/_news.scss
Labels: ready, 🌐 all sites

#2016 Add client reference for LZR
  data/clients.yml
  source/images/references/lzr.png
Labels: ready, 🇬🇧 en.defacto.nl, 🇳🇱 defacto.nl

#2007 Update cases
  locales/de.yml
  locales/nl.yml
  source/cases/index.html.erb
  source/localizable/gezondheidswezen/_clients.de.html.erb
  source/localizable/index.html.erb
  source/localizable/klanten.html.erb
  source/partials/_cases-overview.erb
  source/stylesheets/posts/_cases.scss
Labels: ready, 🇩🇪 defactolearning.de, 🇳🇱 defacto.nl

#2018 Add AZG logo to references
  data/clients.yml
  source/images/references/ambulancezorg-groningen.png
Labels: ready, 🇬🇧 en.defacto.nl, 🇳🇱 defacto.nl

#2020 Add new logo for 'Amarant'
  data/clients.yml
  data/clients_de.yml
  source/images/references/amarant.png
  source/images/references/amarant.svg
Labels: ready, 🌐 all sites

#2019 Add new logo for 'De Opbouw'
  data/clients.yml
  data/clients_de.yml
  source/images/references/de-opbouw.png
  source/images/references/de-opbouw.svg
Labels: ready, 🌐 all sites
