Repository DefactoSoftware/website, pull requests merged in 2019-10, with the labels that each got.

#2034 Fix the navigations
  data/navigations_de.yml
  data/navigations_en.yml
  data/navigations_nl.yml
  source/partials/footer/_footer-navigation.erb
  source/partials/header/_nav-dropdowns.erb
  source/partials/header/_nav-mobile.erb
  source/partials/header/_nav-primary.erb
Labels: ready, 🌐 all sites

#2041 Update team october 2019
  data/team.yml
  source/images/team/richard-van-der-veen.jpg
Labels: ready, 🌐 all sites

#2042 Update team
  data/team.yml
  source/images/team/klaus-walheim.jpg
Labels: ready, 🌐 all sites

#2043 Re-add NL event calendar and add Next Learning event entry
  source/localizable/evenementen/_events.nl.md.erb
  source/localizable/evenementenagenda.html.erb
Labels: ready, 🇳🇱 defacto.nl

#2044 Fix DE event calendar indentation
  source/localizable/evenementen/_events.de.md.erb
Labels: ready, 🇩🇪 defactolearning.de
