Repository DefactoSoftware/website, pull requests merged in 2019-06, with the labels that each got.

#1892 Update team
  data/team.yml
  source/images/team/frank-te-biesebeek.jpg
Labels: ready, 🌐 all sites

#1893 Smaller news tiles
  locales/de.yml
  locales/nl.yml
  source/localizable/home/_news.erb
  source/stylesheets/sections/_news.scss
Labels: ready, 🇩🇪 defactolearning.de, 🇳🇱 defacto.nl

#1895 Remove passed events from information sessions dropdowns
  source/localizable/informatiesessie.html.erb
Labels: ready, 🇳🇱 defacto.nl

#1898 Remove conversion option
  locales/de.yml
  source/blog/de/2018-09-27-fordermittel-fur-digitale-medien-in-der-beruflichen-bildung-im-gesundheitswesen.html.markdown
  source/localizable/call-to-actions/_information-albert.erb
Labels: ready, 🇩🇪 defactolearning.de

#1899 Clarify form permission text in LMS questionnaire
  source/localizable/wat-voor-lms-past-bij-mij.html.erb
Labels: ready, 🇳🇱 defacto.nl

#1901 Update use of forms for CAPP (LMS) product pages
  data/downloads.yml
  source/localizable/call-to-actions/_download-qualitymonitor-productsheet.erb
  source/localizable/capp-lms-new/_form.erb
  source/localizable/capp-lms-new/_hero.erb
  source/localizable/capp-lms.html.erb
  source/localizable/capp-talent-management.html.erb
  source/localizable/capp-talent-management/_form.erb
  source/localizable/capp-talent-management/_hero.erb
  source/localizable/kwaliteitsmonitor.html.erb
  source/localizable/kwaliteitspaspoort-new/_form.erb
  source/localizable/kwaliteitspaspoort-new/_hero.erb
  source/localizable/kwaliteitspaspoort.html.erb
  source/pdf/Productsheet_Qualitaetspass_Qualitaetsmonitor.pdf
Labels: ready, 🇩🇪 defactolearning.de, 🇳🇱 defacto.nl

#1902 Use form partial on theme pages
  source/localizable/70-20-10.html.erb
  source/localizable/call-to-actions/_information-70-20-10.erb
  source/localizable/call-to-actions/_information-cmt.erb
  source/localizable/call-to-actions/_information-digital-hospital.erb
  source/localizable/call-to-actions/_information-elearning-healthcare.erb
  source/localizable/convenant-medische-technologie.html.erb
  source/localizable/digital-hospital.html.erb
  source/localizable/e-learning-in-healthcare.html.erb
Labels: ready, 🇩🇪 defactolearning.de, 🇳🇱 defacto.nl

#1904 Add new employee image and name to team
  data/team.yml
  source/images/team/laura-piel.jpg
Labels: ready, 🌐 all sites

#1906 Remove empty form class declarations
  source/localizable/capp-lms-new/_hero.erb
  source/localizable/capp-talent-management/_hero.erb
  source/localizable/kwaliteitspaspoort-new/_hero.erb
Labels: ready, 🇩🇪 defactolearning.de, 🇳🇱 defacto.nl

#1910 Update demo request form title for solutions gesundheitswesen form
  locales/de.yml
  source/localizable/gezondheidswezen.html.erb
  source/localizable/gezondheidswezen/_demo-request.erb
Labels: ready, 🇩🇪 defactolearning.de

#1908 Use form partial for kpp form
  source/localizable/call-to-actions/_appointment-kwaliteitspaspoort.erb
  source/localizable/kwaliteitspaspoort.html.erb
  source/stylesheets/pages/_kwaliteitspaspoort.scss
Labels: ready, 🇬🇧 en.defacto.nl, 🇳🇱 defacto.nl

#1907 Use call-to-action partial in designated folders for posts
  source/blog/_call-to-action.erb
  source/blog/de/2018-11-22-kundentag-november-2018.html.markdown
  source/blog/de/2018-12-21-audit-pharmaunternehmen-pohl-boskamp.html.markdown
  source/blog/de/2019-03-14-defacto-gewinnt-die-Sana-ag-als-neuen-kunden.html.markdown
  source/blog/de/2019-05-09-mehr-qualitat-in-der-patientenversorgung.html.markdown
  source/blog/nl/2019-03-14-defacto-verwelkomt-grote-duitse-ziekenhuisgroep-als-klant.html.markdown
  source/blog/nl/2019-03-22-huis-voor-de-sport-groningen-coacht-co-met-capp-agile-learning.html.markdown
  source/blog/nl/2019-05-07-defacto-feliciteert-dianet-hkz-certificering-capp-lms.html.markdown
  source/cases/_call-to-action.erb
  source/cases/de/evangelisches-krankenhaus-oldenburg.html.markdown
  source/cases/de/fek-neumunster.html.markdown
  source/cases/nl/dianet.html.markdown
  source/layouts/post_layout.erb
  source/localizable/call-to-actions/_appointment-case.erb
  source/localizable/partials/_call-to-action.erb
Labels: ready, 🌐 all sites

#1909 Demo request form titles with form partial
  locales/de.yml
  locales/en.yml
  locales/nl.yml
  source/localizable/capp-agile-learning.html.erb
  source/localizable/demo-aanvragen/_hero.erb
  source/stylesheets/pages/_request-demo.scss
Labels: ready, 🌐 all sites

#1903 Use contact form partial on contact page
  source/localizable/capp-agile-learning.html.erb
  source/localizable/contact.html.erb
  source/localizable/informatiesessie.html.erb
  source/partials/_form.erb
  source/stylesheets/pages/_capp-agile-learning.scss
Labels: ready, 🌐 all sites

#1913 Add L. Bonder to team and update employee image
  data/team.yml
  source/images/team/lidia-bonder.jpg
  source/images/team/marleen-renshoff.jpg
Labels: ready, 🌐 all sites

#1914 Update newsletter subscribing text in footer
  locales/de.yml
Labels: ready, 🇩🇪 defactolearning.de

#1917 Update client
  data/clients.yml
  data/clients_de.yml
  source/images/references/sheerenloo.png
  source/images/references/sheerenloo.svg
Labels: ready, 🌐 all sites

#1916 Use form partial for upgrade sheet download
  source/localizable/call-to-actions/_information-migration.erb
  source/localizable/upgrade.html.erb
Labels: ready, 🇳🇱 defacto.nl

#1915 Use form partial for ebook download
  source/localizable/call-to-actions/_download-ebook.erb
  source/localizable/e-book-leren-en-laten-leren.html.erb
  source/localizable/e-learning.html.erb
Labels: ready, 🌐 all sites

#1918 Use form partial for quizzes productsheet
  source/localizable/call-to-actions/_information-quizzes.nl.erb
  source/localizable/quizzes.html.erb
Labels: ready, 🇳🇱 defacto.nl

#1919 Change title of compliance api conversion form
  source/localizable/compliance-api.html.erb
  source/localizable/compliance-api/_conversion.nl.erb
Labels: ready, 🇳🇱 defacto.nl

#1920 Use form partial on implementations page
  source/localizable/call-to-actions/_information-joost.erb
  source/localizable/implementaties.html.erb
Labels: ready, 🇳🇱 defacto.nl

#1921 Minor edits on other conversions
  locales/de.yml
  source/blog/de/2018-10-15-cme-punkte-schnell-erfassen-mit-capp-lms.html.markdown
  source/blog/nl/2017-12-18-defacto-presenteert-nieuwe-capp-versie.html.markdown
  source/blog/nl/2018-05-09-stadjer-zoekt-umc-umc-zoekt-lms.html.markdown
  source/localizable/360-feedback.html.erb
  source/localizable/call-to-actions/_360-feedback.erb
  source/localizable/call-to-actions/_appointment-cme.erb
  source/localizable/call-to-actions/_demo-request.erb
  source/localizable/call-to-actions/_information-capp12.erb
  source/localizable/call-to-actions/_information-event.erb
Labels: ready, 🌐 all sites

#1922 Change name lms questionnaire form
  source/localizable/wat-voor-lms-past-bij-mij.html.erb
Labels: ready, 🇳🇱 defacto.nl

#1923 Use contact request as title for solution form
  locales/de.yml
  source/localizable/performance-support/_conversion.html.erb
  source/localizable/webinar.html.erb
Labels: ready, 🌐 all sites

#1924 Remove demo page
  locales/de.yml
  locales/en.yml
  locales/nl.yml
  source/images/icons/icon-demo.svg
  source/localizable/contact/_contact.md.erb
  source/localizable/demo-aanvragen.html.erb
  source/localizable/header/_nav-mobile.erb
  source/localizable/header/_nav-primary.erb
  source/localizable/home/_hero.erb
  source/stylesheets/layout/_header.scss
  source/stylesheets/pages/_contact.scss
  source/stylesheets/pages/_request-demo.scss
Labels: ready, 🌐 all sites

#1926 Update whitepaper form title
  source/localizable/performance-support-whitepaper.html.erb
Labels: ready, 🇩🇪 defactolearning.de

#1925 Fix informatie sessie form
  source/localizable/informatiesessie.html.erb
  source/partials/_form.erb
  source/stylesheets/base/_buttons.scss
Labels: ready, 🇳🇱 defacto.nl

#1928 Center the title on the overview of a product
  source/localizable/capp-lms-new/_overview.nl.erb
  source/stylesheets/pages/_capp-lms-new.scss
Labels: ready, 🌐 all sites

#1927 Add new webinars
  data/redirects_de.yml
  locales/de.yml
  source/localizable/evenementen/_events.de.md.erb
  source/localizable/webinar-compliance-und-qualifikationsmanagement-16-07-2019.html.erb
  source/localizable/webinar-compliance-und-qualifikationsmanagement-18-07-2019.html.erb
  source/localizable/webinar-curated-learning-04-07-2019.html.erb
  source/localizable/webinar-performance-support-03-09-2019.html.erb
  source/localizable/webinar/_content.de.md
Labels: ready, 🇩🇪 defactolearning.de
