Repository DefactoSoftware/website, pull requests merged in 2019-03, with the labels that each got.

#1714 Fix missing background image for intro on CAPP pages
  source/stylesheets/pages/_capp-lms-new.scss
Labels: ready, 🌐 global

#1713 Fix offsettop for scrollto functionality
  source/javascripts/_scroll-to.js
Labels: ready, 🌐 global

#1715 Add Martha to team
  data/team.yml
  source/images/team/martha-jorna.jpg
Labels: ready, 🌐 global

#1716 Use article on introduction sections on CAPP productpages
  source/localizable/capp-lms-new/_introduction.de.erb
  source/localizable/capp-talent-management/_introduction.erb
  source/localizable/kwaliteitspaspoort-new/_introduction.de.erb
Labels: ready, 🇩🇪 defactolearning.de

#1718 Fix width of last box on new Compliance page
  source/localizable/capp-lms-new/_overview.de.erb
  source/localizable/capp-lms-new/_overview.nl.erb
  source/localizable/kwaliteitspaspoort-new/_overview.de.erb
  source/stylesheets/pages/_capp-lms-new.scss
Labels: ready, 🇩🇪 defactolearning.de

#1719 Add a list style for bulleted list component
  source/localizable/capp-talent-management/_overview.erb
  source/stylesheets/components/_lists.scss
Labels: ready, 🌐 global

#1723 Fix cases quote
  source/cases/de/fek-neumunster.html.markdown
  source/stylesheets/posts/_case-sidebar.scss
Labels: ready

#1724 Fix link to emberjs.com
  source/blog/en/2015-05-20-animated-loading-indicator-with-isometric-cubes.html.markdown
  source/blog/nl/2015-05-20-animated-loading-indicator-with-isometric-cubes.html.markdown
Labels: ready, 🇬🇧 en.defacto.nl, 🇳🇱 defacto.nl

#1726 Add SANA testimonial
  data/testimonials_de.yml
  source/images/testimonials/jutta-geringhoff.jpg
Labels: ready, 🇩🇪 defactolearning.de

#1727 Add page for e-learning in healthcare in 'themes'
  locales/de.yml
  source/images/moods/healthcare.jpg
  source/localizable/call-to-actions/_information-elearning-healthcare.erb
  source/localizable/e-learning-in-healthcare.html.erb
  source/localizable/e-learning.html.erb
  source/localizable/elearning-in-healthcare/_content.md.erb
  source/localizable/elearning/_elearning.de.md.erb
  source/localizable/themas/_themas.md.erb
  source/stylesheets/pages/_elearning-in-healthcare.scss
  source/stylesheets/pages/_producten.scss
Labels: ready, 🇩🇪 defactolearning.de

#1728 Add Next Learning event to news
  data/news_nl.yml
  source/images/news/masies-news.jpg
  source/images/news/next-learning-2019.jpg
Labels: ready, 🇳🇱 defacto.nl

#1732 Fix link to RIVM
  source/blog/nl/2017-11-28-rivm-wint-award-beste-corporate-academy.html.markdown
Labels: ready

#1737 Use Ruby 2.4.3
  .ruby-version
  README.md
Labels: ready, 🌐 global

#1738 Use https in old blog
  source/blog/en/2015-05-20-animated-loading-indicator-with-isometric-cubes.html.markdown
  source/blog/nl/2015-05-20-animated-loading-indicator-with-isometric-cubes.html.markdown
Labels: ready, 🇬🇧 en.defacto.nl, 🇳🇱 defacto.nl

#1739 Remove staging
  README.md
  Rakefile
Labels: ready, 🌐 global

#1710 Add a part about solutions
  locales/de.yml
  source/cases/de/evangelisches-krankenhaus-oldenburg.html.markdown
  source/cases/de/fek-neumunster.html.markdown
  source/images/icons/healthcare.svg
  source/images/screenshots/gesundheitswesen-qualitatspass.png
  source/images/screenshots/gesundheitswesen-schulungen.png
  source/localizable/capp-lms-new/_on-page-navigation.erb
  source/localizable/capp-lms.html.erb
  source/localizable/capp-talent-management.html.erb
  source/localizable/capp-talent-management/_on-page-navigation.erb
  source/localizable/gezondheidswezen.html.erb
  source/localizable/gezondheidswezen/_clients.de.html.erb
  source/localizable/gezondheidswezen/_demo-request.html.erb
  source/localizable/gezondheidswezen/_hero.html.erb
  source/localizable/gezondheidswezen/_introductie.de.md
  source/localizable/gezondheidswezen/_leerplatform.de.html.erb
  source/localizable/gezondheidswezen/_more.de.html.erb
  source/localizable/gezondheidswezen/_on-page-navigation.html.erb
  source/localizable/header/_nav-dropdowns.erb
  source/localizable/header/_nav-mobile.erb
  source/localizable/header/_nav-primary.erb
  source/localizable/kwaliteitspaspoort-new/_on-page-navigation.erb
  source/localizable/kwaliteitspaspoort.html.erb
  source/localizable/oplossingen.html.erb
  source/localizable/oplossingen/_oplossingen.html.de.erb
  source/localizable/partials/_featured-testimonial.erb
  source/partials/_form.erb
  source/stylesheets/base/_grid-settings.scss
  source/stylesheets/components/_on-page-navigation.scss
  source/stylesheets/pages/_capp-lms-new.scss
  source/stylesheets/pages/_gezondheidswezen.scss
  source/stylesheets/pages/_producten.scss
Labels: ready, 🇩🇪 defactolearning.de

#1740 Add and feature Sana Pressebericht
  data/news_de.yml
  source/blog/de/2018-12-21-audit-pharmaunternehmen-pohl-boskamp.html.markdown
  source/blog/de/2019-03-14-defacto-gewinnt-die-Sana-ag-als-neuen-kunden.html.markdown
  source/images/blog/featured/20190314-sana.jpg
  source/images/blog/social/sana-1200x630.jpg
  source/images/moods/sana-mood.jpg
  source/images/news/sana-news.jpg
Labels: copy, ready, 🇩🇪 defactolearning.de

#1743 Update content, testimonial and add logo to healthcare page
  data/testimonials_de.yml
  source/localizable/gezondheidswezen/_clients.de.html.erb
  source/localizable/gezondheidswezen/_introductie.de.md
  source/localizable/gezondheidswezen/_leerplatform.de.html.erb
Labels: ready, 🇩🇪 defactolearning.de

#1746 Update FEK testimonial
  data/testimonials_de.yml
  source/images/testimonials/anne-merlind-monier.jpg
  source/images/testimonials/christof-thielecke.jpg
Labels: ready, 🇩🇪 defactolearning.de

#1745 Update products & services on Germaanse cases
  source/cases/de/evangelisches-krankenhaus-oldenburg.html.markdown
  source/cases/de/fek-neumunster.html.markdown
  source/cases/de/mumc.html.markdown
  source/cases/de/strukton.html.markdown
  source/cases/de/zinn.html.markdown
Labels: ready, 🇩🇪 defactolearning.de

#1753 Add Sana blog post to Dutch website
  data/news_nl.yml
  source/blog/nl/2018-12-04-audit-farmaceutisch-bedrijf-pohl-boskamp.html.markdown
  source/blog/nl/2019-03-14-defacto-verwelkomt-grote-duitse-ziekenhuisgroep-als-klant.html.markdown
Labels: ready, 🇳🇱 defacto.nl

#1751 Use better argument for when we need no open graph
  source/layouts/layout.erb
  source/localizable/404.html.erb
  source/localizable/bedankt.html.erb
Labels: ready, 🌐 global

#1756 Create new blog post about Huis voor de Sport
  data/news_nl.yml
  source/blog/nl/2019-03-22-huis-voor-de-sport-groningen-coacht-co-met-capp-agile-learning.html.markdown
  source/images/blog/capp-agile-learning-huisvoordesport.jpg
  source/images/blog/featured/20190322-huis-voor-de-sport.jpg
  source/images/blog/social/huis-voor-de-sport-860x630.jpg
  source/images/moods/huis-voor-de-sport-mood.jpg
  source/images/news/huis-voor-de-sport-news.jpg
Labels: ready, 🇳🇱 defacto.nl

#1760 Add links to CAPP LMS in Sana blog
  source/blog/nl/2019-03-14-defacto-verwelkomt-grote-duitse-ziekenhuisgroep-als-klant.html.markdown
Labels: 🇳🇱 defacto.nl

#1761 Add links to product pages
  locales/de.yml
  source/localizable/capp-lms-new/_more.de.erb
  source/localizable/capp-lms.html.erb
  source/localizable/capp-talent-management.html.erb
  source/localizable/capp-talent-management/_more.de.erb
  source/localizable/gezondheidswezen/_more.de.html.erb
  source/localizable/kwaliteitspaspoort-new/_more.de.erb
  source/localizable/kwaliteitspaspoort.html.erb
  source/stylesheets/pages/_gezondheidswezen.scss
  source/stylesheets/sections/_call-to-actions.scss
  source/stylesheets/sections/_more-about.scss
Labels: ready, 🇩🇪 defactolearning.de

#1747 Add Compliance API landing page
  data/downloads.yml
  source/images/moods/bridge.jpg
  source/images/screenshots/compliance-api-toepassingen.png
  source/localizable/call-to-actions/_information-compliance-api.nl.erb
  source/localizable/compliance-api.html.erb
  source/localizable/compliance-api/_content.nl.md
  source/pdf/Productsheet_Compliance_API.pdf
  source/stylesheets/pages/_compliance-api.scss
Labels: ready, 🇳🇱 defacto.nl

#1764 Update news image
  source/images/news/huis-voor-de-sport-news.jpg
Labels: ready, 🇳🇱 defacto.nl

#1765 Update featured blog image
  source/images/blog/featured/20190322-huis-voor-de-sport.jpg
Labels: ready, 🇳🇱 defacto.nl

#1766 Fix Compliance API landing page form and text
  source/localizable/call-to-actions/_information-compliance-api.nl.erb
  source/stylesheets/pages/_compliance-api.scss
Labels: ready, 🇳🇱 defacto.nl

#1767 Change propduct sheet pdf to final version
  source/pdf/Productsheet_Compliance_API.pdf
Labels: ready, 🇳🇱 defacto.nl

#1769 Add Quizzes landing page
  data/downloads.yml
  source/images/logos/logo-quizzes.png
  source/images/logos/logo-quizzes.svg
  source/images/moods/doors.jpg
  source/images/screenshots/quizzes-screenshots.png
  source/localizable/call-to-actions/_information-quizzes.nl.erb
  source/localizable/quizzes.html.erb
  source/localizable/quizzes/_content.nl.md
  source/pdf/Productsheet_Quizzes.pdf
  source/stylesheets/pages/_quizzes.scss
Labels: ready, 🇳🇱 defacto.nl

#1770 Fix form width in Compliance API landing page
  source/localizable/call-to-actions/_information-compliance-api.nl.erb
  source/localizable/call-to-actions/_information-quizzes.nl.erb
  source/stylesheets/pages/_compliance-api.scss
Labels: ready, 🇳🇱 defacto.nl

#1768 Remove no longer needed deploy and update readme
  Gemfile
  README.md
  Rakefile
  config.rb
Labels: ready, 🌐 all 3 sites

#1778 Replace faulty product sheet pdf with correct one
  source/pdf/Productsheet_Quizzes.pdf
Labels: ready, 🇳🇱 defacto.nl
