Repository DefactoSoftware/website, pull requests merged in 2019-09, with the labels that each got.

#2021 Add Leviaan to references
  data/clients.yml
  source/images/references/leviaan.png
Labels: ready, 🇳🇱 defacto.nl

#2023 Add RAV Brabant MWN reference
  data/clients.yml
  source/images/references/rav-brabant-mwn.png
Labels: ready, 🇳🇱 defacto.nl

#2022 Add Radboud Universiteit to references
  data/clients.yml
  source/images/references/ru.svg
Labels: ready, 🇳🇱 defacto.nl

#2024 Add De Jong & Laan reference
  data/clients.yml
  source/images/references/jong-en-laan.svg
Labels: ready, 🇳🇱 defacto.nl

#2026 Add LZR case study
  source/cases/nl/laurentius-ziekenhuis.html.markdown
  source/images/cases/lzr/logo-laurentius-wit.png
  source/images/cases/lzr/lzr-social.jpg
  source/images/cases/lzr/mood-lzr.jpg
Labels: ready, 🇳🇱 defacto.nl

#2029 Add Lunet zorg to references
  data/clients.yml
  source/images/references/lunet-zorg.png
Labels: ready, 🇳🇱 defacto.nl

#2028 Add JHF to references
  data/clients.yml
  source/images/references/jeugdhulp-friesland.png
Labels: ready, 🇳🇱 defacto.nl

#2027 Update testimonials
  data/testimonials_nl.yml
  source/images/testimonials/desiree-hintzen.jpg
Labels: ready, 🇳🇱 defacto.nl

#2031 Update service & support styling
  source/stylesheets/pages/_support.scss
Labels: ready, 🇩🇪 defactolearning.de, 🇳🇱 defacto.nl

#2032 Update sentence about us
  source/localizable/over-ons/_over-ons.nl.md.erb
Labels: ready, 🇳🇱 defacto.nl

#2033 Move Service & Support to Diensten/Service
  data/navigations_de.yml
  data/navigations_nl.yml
Labels: ready, 🇩🇪 defactolearning.de, 🇳🇱 defacto.nl

#2036 Add number of CAPP LMS users
  data/navigations_nl.yml
  locales/nl.yml
Labels: ready, 🇳🇱 defacto.nl

#2037 Update key user event RSVP page
  source/localizable/key-user-event.html.erb
  source/localizable/key-user-event/_content.nl.md
Labels: ready, 🇳🇱 defacto.nl

#2038 Remove old DE events
  source/localizable/evenementen/_events.de.md.erb
  source/localizable/webinar-performance-support-03-09-2019.html.erb
Labels: ready, 🇩🇪 defactolearning.de
