Repository DefactoSoftware/website, pull requests merged in 2019-01, with the labels that each got.

#1664 Add service desk job
  data/news_de.yml
  source/jobs/de/mitarbeiter-service-desk.html.markdown
Labels: post, ready, 🇩🇪 defactolearning.de

#1666 Add supportteam consultancy job
  source/jobs/nl/support-consultant.html.markdown.erb
Labels: post, 🇳🇱 defacto.nl

#1663 Update more articles title
  locales/nl.yml
Labels: ready, 🇳🇱 defacto.nl

#1670 Add Vortrag link to Learntec event description
  source/localizable/evenementenagenda/_events.de.md.erb
Labels: ready, 🇩🇪 defactolearning.de

#1672 Translate CAPP Bilden to CAPP Talent Management
  data/redirects_de.yml
  locales/de.yml
  locales/en.yml
  locales/nl.yml
  source/blog/de/2015-07-03-nur-zufriedener-kunde-ein-guter-kunde.html.markdown
  source/blog/de/2016-10-04-capp-talentmanagement-im-gesundheitswesen.html.markdown
  source/blog/de/2016-10-25-qualitat-sichern-durch-bildungsmanagement.html.markdown
  source/blog/de/2016-11-03-schon-wieder-ein-neues-system.html.markdown
  source/blog/de/2016-12-05-warum-unsere-geschichte-so-wichtig-ist.html.markdown
  source/blog/de/2017-01-25-neuer-kunde-klinikum-itzehoe.html.markdown
  source/blog/de/2017-05-09-von-krankenschwester-zur-softwareexpertin.html.markdown
  source/blog/de/2017-11-23-learning-2017-drei-wichtigsten-erkenntnisse.html.markdown
  source/blog/de/2018-04-30-neuer-kunde-medius-kliniken.html.markdown
  source/blog/de/2018-06-14-medizinischer-fachangestellter-im-krankenhaus-entlastung-fur-den-arzt.html.markdown
  source/blog/de/2018-07-09-fort-und-weiterbildung-fur-medizinische-fachangestellte-gute-perspektiven.html.markdown
  source/blog/de/2018-10-15-cme-punkte-schnell-erfassen-mit-capp-lms.html.markdown
  source/cases/de/evangelisches-krankenhaus-oldenburg.html.markdown
  source/cases/de/fek-neumunster.html.markdown
  source/cases/de/mumc.html.markdown
  source/cases/de/strukton.html.markdown
  source/cases/de/zinn.html.markdown
  source/images/moods/healthcare.jpg
  source/localizable/elearning/_elearning.de.md.erb
  source/localizable/header/_nav-dropdowns.erb
  source/localizable/header/_nav-mobile.erb
  source/localizable/home/_copy.de.erb
  source/localizable/home/_hero.erb
  source/localizable/home/_solutions.erb
  source/localizable/producten/_producten.de.md.erb
  source/localizable/themas/_digital-hospital.de.md.erb
  source/stylesheets/pages/_home.scss
Labels: ready, 🇩🇪 defactolearning.de

#1673 Update the other product paths and page classes
  data/redirects_de.yml
  helpers/page_classes.rb
  locales/de.yml
  source/blog/de/2016-10-04-capp-talentmanagement-im-gesundheitswesen.html.markdown
  source/cases/de/evangelisches-krankenhaus-oldenburg.html.markdown
  source/cases/de/fek-neumunster.html.markdown
  source/cases/de/strukton.html.markdown
  source/cases/de/zinn.html.markdown
  source/localizable/capp-talent-management.html.erb
  source/localizable/header/_nav-dropdowns.erb
  source/localizable/header/_nav-mobile.erb
  source/localizable/home/_copy.de.erb
  source/localizable/home/_solutions.erb
  source/localizable/producten/_producten.de.md.erb
Labels: ready, 🇩🇪 defactolearning.de

#1674 Update learning management page
  locales/de.yml
  locales/nl.yml
  source/images/screenshots/capp-lms/learning-1-dashboard_de.png
  source/images/screenshots/capp-lms/learning-2-schulungen_de.png
  source/images/screenshots/capp-lms/learning-3-highlights_de.png
  source/localizable/call-to-actions/_information-capp12.erb
  source/localizable/capp-lms-new/_form.erb
  source/localizable/capp-lms-new/_hero.erb
  source/localizable/capp-lms-new/_introduction.de.erb
  source/localizable/capp-lms-new/_introduction.nl.erb
  source/localizable/capp-lms-new/_overview.de.erb
  source/localizable/capp-lms-new/_overview.nl.erb
  source/localizable/capp-lms-new/_page-nav.erb
  source/localizable/capp-lms.html.erb
  source/localizable/header/_nav-dropdowns.erb
  source/localizable/header/_nav-mobile.erb
  source/stylesheets/pages/_capp-lms-new.scss
  source/stylesheets/pages/_capp-lms-old.scss
Labels: ready, 🇩🇪 defactolearning.de

#1676 Update capp talent management page
  locales/de.yml
  source/images/icons/capp-develop-pink.svg
  source/images/screenshots/capp-lms/talent-1-leistungen_de.png
  source/images/screenshots/capp-lms/talent-2-skills_de.png
  source/localizable/capp-talent-management.html.erb
  source/localizable/capp-talent-management/_form.erb
  source/localizable/capp-talent-management/_hero.erb
  source/localizable/capp-talent-management/_introduction.erb
  source/localizable/capp-talent-management/_overview.erb
  source/localizable/capp-talent-management/_page-nav.erb
  source/localizable/header/_nav-dropdowns.erb
  source/localizable/header/_nav-mobile.erb
  source/localizable/home/_solutions.erb
Labels: ready, 🇩🇪 defactolearning.de

#1675 Add missing nl translations
  locales/nl.yml
Labels: ready, 🇳🇱 defacto.nl

#1677 Update qualitatspass/compliance management page
  locales/de.yml
  source/images/icons/compliance-pink.svg
  source/images/screenshots/capp-lms/compliance-1-dashboard_de.png
  source/images/screenshots/capp-lms/compliance-2-anforderungen_de.png
  source/localizable/header/_nav-dropdowns.erb
  source/localizable/header/_nav-mobile.erb
  source/localizable/home/_solutions.erb
  source/localizable/kwaliteitspaspoort-new/_form.erb
  source/localizable/kwaliteitspaspoort-new/_hero.erb
  source/localizable/kwaliteitspaspoort-new/_introduction.de.erb
  source/localizable/kwaliteitspaspoort-new/_overview.de.erb
  source/localizable/kwaliteitspaspoort-new/_page-nav.erb
  source/localizable/kwaliteitspaspoort-old/_hero.erb
  source/localizable/kwaliteitspaspoort-old/_kwaliteitspaspoort.de.md.erb
  source/localizable/kwaliteitspaspoort-old/_kwaliteitspaspoort.en.md.erb
  source/localizable/kwaliteitspaspoort-old/_kwaliteitspaspoort.nl.md.erb
  source/localizable/kwaliteitspaspoort.html.erb
  source/localizable/producten/_producten.de.md.erb
Labels: ready, 🇩🇪 defactolearning.de

#1680 Fix z-indexes
  source/stylesheets/components/_intercom-launcher.scss
  source/stylesheets/layout/_header.scss
Labels: ready, 🌐 global
