Repository DefactoSoftware/website, pull requests merged in 2019-02, with the labels that each got.

#1682 Update CAPP Agile Learning text
  source/localizable/capp-agile-learning/_content.de.erb
Labels: ready, 🇩🇪 defactolearning.de

#1691 Add handelsregister id
  source/localizable/impressum.html.erb
  source/localizable/impressum/_impressum.de.md.erb
Labels: copy, 🇩🇪 defactolearning.de

#1694 Remove mitarbeiter im marketing job
  source/jobs/de/mitarbeiter-im-marketing.html.markdown
Labels: ready, 🇩🇪 defactolearning.de

#1695 Update copy consultant job
  data/redirects_de.yml
  source/jobs/de/e-learning-consultant.html.markdown
  source/jobs/de/projektleiter-consultant-softwareimplementierung.html.markdown
Labels: ready, 🇩🇪 defactolearning.de

#1696 Add missing text to job
  source/jobs/nl/support-consultant.html.markdown.erb
Labels: ready, 🇳🇱 defacto.nl

#1698 Remove unused emails from team.yml
  data/team.yml
Labels: ready, 🌐 global

#1697 Add me to team
  data/team.yml
  source/images/team/michel-lusthof.jpg
Labels: ready, 🌐 global

#1699 Align the testimonial h2 centered
  source/stylesheets/pages/_capp-agile-learning.scss
Labels: ready, 🌐 global

#1700 Lennart/update featured events
  data/news_de.yml
  data/news_nl.yml
  source/images/news/learntec-news.jpg
Labels: 🇩🇪 defactolearning.de, 🇳🇱 defacto.nl

#1701 Update eventcalenders with Next Learning event
  source/localizable/evenementenagenda/_events.de.md.erb
  source/localizable/evenementenagenda/_events.nl.md.erb
Labels: ready, 🇩🇪 defactolearning.de, 🇳🇱 defacto.nl

#1702 Update screenshots Kwaliteitspaspoort to CAPP12
  source/images/screenshots/capp-kwaliteitspaspoort-manager.png
  source/images/screenshots/capp12-kwaliteitspaspoort-manager.png
  source/images/screenshots/hero-kwaliteitspaspoort.png
  source/localizable/kwaliteitspaspoort-old/_kwaliteitspaspoort.nl.md.erb
Labels: enhancement, ready, 🇳🇱 defacto.nl

#1703 Add phone to phorms
  source/localizable/call-to-actions/_appointment-case.erb
  source/localizable/call-to-actions/_appointment-cme.erb
  source/localizable/call-to-actions/_appointment-kwaliteitspaspoort.erb
  source/localizable/call-to-actions/_download-capp11-productsheet.erb
  source/localizable/call-to-actions/_download-ebook.erb
  source/localizable/call-to-actions/_download-qualitymonitor-productsheet.erb
  source/localizable/call-to-actions/_information-70-20-10.erb
  source/localizable/call-to-actions/_information-albert.erb
  source/localizable/call-to-actions/_information-cmt.erb
  source/localizable/call-to-actions/_information-digital-hospital.erb
  source/localizable/call-to-actions/_information-joost.erb
  source/localizable/capp-agile-learning.html.erb
  source/localizable/capp-lms-new/_form.erb
  source/localizable/demo-aanvragen/_hero.erb
  source/localizable/productsheet-downloaden.html.erb
  source/stylesheets/pages/_capp-agile-learning.scss
  source/stylesheets/pages/_capp-lms-new.scss
  source/stylesheets/sections/_call-to-actions.scss
Labels: ready, 🌐 global

#1707 Update team
  data/team.yml
  source/images/team/marian-joustra.jpg
Labels: ready, 🌐 global

#1709 Add Sana to clients
  data/clients.yml
  data/clients_de.yml
  source/images/clients/mono/logo-sana-kliniken.svg
  source/images/clients/sana-kliniken.png
  source/images/references/sana-kliniken.png
  source/localizable/capp-agile-learning/_clients.de.erb
  source/localizable/capp-agile-learning/_clients.en.erb
  source/localizable/capp-agile-learning/_clients.nl.erb
  source/localizable/clients/_clients-section.de.md.erb
Labels: ready, 🌐 global

#1706 Add migration page (or: how to make a landing page with Middleman)
  data/downloads.yml
  source/images/screenshots/capp-lms/capp-lms-login.png
  source/localizable/call-to-actions/_information-migration.erb
  source/localizable/migration/_content.nl.md
  source/localizable/update.html.erb
  source/pdf/Productsheet_Migratie.pdf
  source/stylesheets/pages/_update.scss
Labels: ready, 🇳🇱 defacto.nl
