Repository DefactoSoftware/website, pull requests merged in 2019-04, with the labels that each got.

#1782 Remove broken link
  source/blog/de/2017-07-05-defacto-gibt-es-seit-30-jahren.html.markdown
  source/blog/en/2017-07-11-defacto-30-years.html.markdown
  source/blog/nl/2017-07-18-de-geschiedenis-van-onze-stadsvilla.html.markdown
Labels: ready, 🇳🇱 defacto.nl

#1783 Update readme with dependabot
  README.md
Labels: ready, 🌐 all 3 sites

#1784 Add a row container to team partial
  source/localizable/over-ons/_team.erb
  source/stylesheets/config/_variables.scss
  source/stylesheets/sections/_team.scss
Labels: ready, 🌐 all 3 sites

#1786 Update too yellow pic to be less yellow 🎨
  source/images/team/martha-jorna.jpg
Labels: ready, 🌐 all 3 sites

#1797 Update Next Learning text and link
  data/news_nl.yml
Labels: ready, 🇳🇱 defacto.nl

#1798 Use https links where applicable
  source/blog/en/2018-10-22-flexible-cover-images-using-intrinsic-ratio.html.markdown
  source/blog/en/2018-10-24-color-placeholders-for-loading-images.html.markdown
  source/blog/nl/2015-08-12-redesigning-capp.html.markdown
  source/blog/nl/2015-09-17-throwback-thursday-samen-met-fc-groningen-het-internet-op.html.markdown
  source/blog/nl/2016-03-17-nieuw-geleerd-nieuw-gedaan.html.markdown
  source/blog/nl/2016-07-12-bedrijfsuitje-defacto-2016.html.markdown
  source/blog/nl/2016-07-18-alweer-een-systeem.html.markdown
  source/blog/nl/2016-10-05-gebruikersoverleg-22-september-2016.html.markdown
  source/blog/nl/2016-11-28-capp-agile-learning-op-websummit.html.markdown
  source/blog/nl/2017-04-22-flexible-cover-images-using-intrinsic-ratio.html.markdown
  source/blog/nl/2017-07-14-ken-je-potentie-kenniswerker.html.markdown
  source/blog/nl/2017-08-28-kennisoverdracht-realiseren.html.markdown
  source/blog/nl/2017-09-21-verslag-elixirconf-us-2017.html.markdown
  source/blog/nl/2017-10-09-teamwork-opnieuw-gedefinieerd.html.markdown
  source/blog/nl/2017-10-16-sociaal-cognitieve-leertheorie.html.markdown
  source/blog/nl/2017-10-24-color-placeholders-for-loading-images.html.markdown
  source/blog/nl/2017-11-28-rivm-wint-award-beste-corporate-academy.html.markdown
  source/blog/nl/2018-10-31-customizing-the-intercom-launcher.html.markdown
  source/jobs/nl/elixir-developer.html.markdown.erb
  source/localizable/partials/_social-share.erb
  test.rb
Labels: ready, 🇳🇱 defacto.nl

#1799 Add quick fix to use target blank on news item
  data/news_nl.yml
  source/localizable/home/_news.erb
Labels: ready, 🇳🇱 defacto.nl

#1800 Update list and images of team in april 2019
  data/team.yml
  source/images/team/christa-vlaanderen.jpg
  source/images/team/frank-te-biesebeek.jpg
  source/images/team/martha-jorna.jpg
  source/images/team/tim-bakker.jpg
Labels: ready, 🌐 all 3 sites

#1805 Update support team
  source/localizable/support.html.erb
  source/stylesheets/pages/_support.scss
Labels: ready, 🇩🇪 defactolearning.de, 🇳🇱 defacto.nl

#1807 Use https for links where applicable
  source/blog/de/2016-10-25-qualitat-sichern-durch-bildungsmanagement.html.markdown
  source/blog/de/2017-05-22-klinikmanagementpersonal-2017.html.markdown
  source/blog/de/2017-07-31-nutzen-sie-ihr-potenzial.html.markdown
  source/blog/de/2017-08-24-mitarbeiterfuhrung-alles-oder-nichts.html.markdown
  source/blog/de/2017-08-28-wissensvermittlung-in-die-tat-umsetzen.html.markdown
  source/blog/de/2017-09-21-besuch-der-elixirconf-2017-in-der-USA.html.markdown
  source/blog/de/2017-10-09-teamwork-wird-es-neu-definiert.html.markdown
  source/blog/de/2017-10-16-sozialkognitive-lerntheorie-heute.html.markdown
  source/blog/de/2018-06-14-medizinischer-fachangestellter-im-krankenhaus-entlastung-fur-den-arzt.html.markdown
  source/blog/de/2018-07-09-fort-und-weiterbildung-fur-medizinische-fachangestellte-gute-perspektiven.html.markdown
  source/blog/nl/2017-08-28-kennisoverdracht-realiseren.html.markdown
  source/cases/de/evangelisches-krankenhaus-oldenburg.html.markdown
  source/localizable/themas/_cmt.de.md.erb
  test.rb
Labels: ready, 🇩🇪 defactolearning.de

#1806 Fix spacing for CAPP Agile Learning logo on mobile
  source/stylesheets/pages/_capp-agile-learning.scss
Labels: ready, 🌐 all 3 sites

#1804 Use ruby 2.4.3 in circleci setup
  .circleci/config.yml
Labels: ready, 🌐 all 3 sites

#1811 Update the description, content and download of the Update page
  config.rb
  data/downloads.yml
  source/localizable/call-to-actions/_information-migration.erb
  source/localizable/migration/_content.nl.md
  source/localizable/upgrade.html.erb
  source/pdf/Infosheet_Upgrade.pdf
  source/pdf/Productsheet_Migratie.pdf
  source/stylesheets/pages/_upgrade.scss
Labels: 🇳🇱 defacto.nl

#1801 Remove Bowser dependency
  Gemfile
  Gemfile.lock
  source/javascripts/all.js.erb
Labels: ready, 🌐 all sites

#1814 Update redirects
  config.rb
  data/redirects_nl.yml
Labels: ready, 🌐 all sites

#1759 Add Performance Support page to Solutions
  locales/de.yml
  source/images/icons/performance-support.svg
  source/images/screenshots/excel-in-bibliothek.gif
  source/images/screenshots/five-moments-of-need-large_de.jpg
  source/images/screenshots/infographic-performance-support-transparant-DE.png
  source/images/screenshots/qr-code-performance-support-large.png
  source/localizable/header/_nav-dropdowns.erb
  source/localizable/header/_nav-mobile.erb
  source/localizable/oplossingen/_oplossingen.html.de.erb
  source/localizable/performance-support.html.erb
  source/localizable/performance-support/_advantages.de.html.erb
  source/localizable/performance-support/_conversion.html.erb
  source/localizable/performance-support/_hero.html.erb
  source/localizable/performance-support/_introductie.de.md
  source/localizable/performance-support/_moments.de.html.erb
  source/localizable/performance-support/_on-page-navigation.html.erb
  source/localizable/performance-support/_practical.de.html.erb
  source/localizable/performance-support/_products.html.erb
  source/partials/_form.erb
  source/stylesheets/pages/_performance-support.scss
  source/stylesheets/pages/_producten.scss
Labels: ready, 🇩🇪 defactolearning.de

#1815 Add Quizzes and Compliance API to Actueel
  data/news_nl.yml
  source/images/news/compliance-api-news.jpg
  source/images/news/dianet.jpg
  source/images/news/huis-voor-de-sport-news.jpg
  source/images/news/next-learning-2019.jpg
  source/images/news/quizzes-news.jpg
Labels: ready, 🇳🇱 defacto.nl

#1808 Create Compliance API Product Page
  locales/nl.yml
  source/images/compliance-api-toepassingen.png
  source/images/icons/compliance-connecting.svg
  source/images/icons/compliance-management.svg
  source/images/icons/compliance-realtime.svg
  source/images/icons/compliance-safe.svg
  source/images/logos/logo-capp-compliance-api.svg
  source/localizable/call-to-actions/_information-compliance-api.nl.erb
  source/localizable/compliance-api.html.erb
  source/localizable/compliance-api/_applications.nl.erb
  source/localizable/compliance-api/_content.nl.md
  source/localizable/compliance-api/_conversion.nl.erb
  source/localizable/compliance-api/_hero.nl.erb
  source/localizable/compliance-api/_how-it-works.nl.erb
  source/localizable/compliance-api/_on-page-navigation.erb
  source/localizable/compliance-api/_overview.nl.erb
  source/partials/_form.erb
  source/stylesheets/pages/_compliance-api.scss
Labels: ready, 🇳🇱 defacto.nl

#1818 Update management assistant job posting
  source/jobs/nl/management-assistant.html.markdown.erb
Labels: ready, 🇳🇱 defacto.nl

#1819 Update DE Performance Support page infographic
  source/images/screenshots/infographic-performance-support-transparant-DE.png
Labels: ready, 🇩🇪 defactolearning.de

#1821 Update UPGRADE formkeep endpoint and change order of form fields
  locales/nl.yml
  source/localizable/call-to-actions/_information-migration.erb
Labels: ready, 🇳🇱 defacto.nl

#1822 Replace title of downloadable pdf (upgrade page)
  source/pdf/Infosheet_Upgrade.pdf
Labels: ready, 🇳🇱 defacto.nl

#1823 Update news item titles and descriptions
  data/news_nl.yml
Labels: ready, 🇳🇱 defacto.nl

#1826 Remove case
  data/testimonials_nl.yml
  source/blog/nl/2018-11-14-defacto-klantendag-november-2018.html.markdown
  source/cases/nl/antoni-van-leeuwenhoek.html.markdown
  source/images/cases/avl/logo-white.png
  source/images/cases/avl/mood.jpg
  source/images/cases/avl/social.jpg
  source/images/testimonials/miriam-boer.jpg
  source/localizable/evenementenagenda/gebruikersbijeenkomst-november-2018.nl.html.erb
  source/localizable/implementaties/_implementaties.nl.md.erb
Labels: ready, 🇳🇱 defacto.nl

#1827 Add Bear Necessities to open source page!
  source/images/open-source/bear-necessities.png
  source/localizable/open-source.html.erb
Labels: ready, 🌐 all sites

#1825 Block tag pages from googlebot
  source/robots.txt.erb
  source/sitemap.xml.builder
Labels: ready, 🇩🇪 defactolearning.de, 🇳🇱 defacto.nl

#1809 Introducing font weight vars
  source/stylesheets/base/_buttons.scss
  source/stylesheets/base/_form-elements.scss
  source/stylesheets/base/_tables.scss
  source/stylesheets/base/_typography.scss
  source/stylesheets/components/_code.scss.erb
  source/stylesheets/components/_hero.scss
  source/stylesheets/components/_on-page-navigation.scss
  source/stylesheets/components/_sidebar.scss
  source/stylesheets/config/_variables.scss
  source/stylesheets/layout/_header.scss
  source/stylesheets/pages/_capp-agile-learning.scss
  source/stylesheets/pages/_capp-lms-new.scss
  source/stylesheets/pages/_capp-lms-old.scss
  source/stylesheets/pages/_download-productsheet.scss
  source/stylesheets/pages/_evenementenagenda.scss
  source/stylesheets/pages/_home.scss
  source/stylesheets/pages/_kwaliteitsmonitor.scss
  source/stylesheets/pages/_kwaliteitspaspoort.scss
  source/stylesheets/pages/_open-source.scss
  source/stylesheets/pages/_producten.scss
  source/stylesheets/pages/_request-demo.scss
  source/stylesheets/pages/_search.scss
  source/stylesheets/pages/_support.scss
  source/stylesheets/posts/_blog-article-preview.scss
  source/stylesheets/posts/_blog.scss
  source/stylesheets/posts/_case-sidebar.scss
  source/stylesheets/posts/_page-controls.scss
  source/stylesheets/posts/_post-header.scss
  source/stylesheets/posts/_posts.scss
  source/stylesheets/sections/_feature-list.scss
  source/stylesheets/sections/_news.scss
  source/stylesheets/sections/_social-share.scss
  source/stylesheets/sections/_solutions.scss
  source/stylesheets/sections/_team.scss
Labels: ready, 🌐 all sites

#1828 Remove team members
  data/team.yml
  source/images/team/cathrin-prins.jpg
  source/images/team/ellen-westerveld.jpg
Labels: ready, 🌐 all sites

#1830 Remove link to langevin
  source/blog/en/2015-05-21-give-them-knowledge-and-games.html.markdown
Labels: ready, 🇬🇧 en.defacto.nl
