Repository DefactoSoftware/website, pull requests merged in 2019-07, with the labels that each got.

#1929 Use search_index instead of index as key
  config.rb
  source/blog/index.html.erb
  source/blog/tag.html.erb
  source/blog/tags.html.erb
  source/cases/index.html.erb
  source/jobs/index.html.erb
  source/localizable/404.html.erb
  source/localizable/bedankt.html.erb
  source/localizable/informatiesessie.html.erb
  source/localizable/quizzes.html.erb
  source/localizable/upgrade.html.erb
  source/localizable/wat-voor-lms-past-bij-mij/resultaten.html.erb
  source/localizable/zoeken.html.erb
Labels: ready, 🌐 all sites

#1875 Move partials to folder outside localizable
  source/partials/_call-to-action.erb
  source/partials/_contact-info.erb
  source/partials/_featured-testimonial.erb
  source/partials/_feed.erb
  source/partials/_intercom.erb
  source/partials/_privacy-notification.erb
  source/partials/_related-posts.erb
  source/partials/_social-proof.erb
  source/partials/_social-share.erb
  source/partials/_testimonials.erb
Labels: ready, 🌐 all sites

#1931 Add infosheet PDF
  source/pdf/Infosheet_Mijn_lijst.pdf
Labels: ready, 🇳🇱 defacto.nl

#1930 Fix failing decoding of downloaded font
  source/stylesheets/base/_fonts.scss
Labels: ready, 🌐 all sites

#1933 Clearer language switch
  locales/de.yml
  locales/en.yml
  locales/nl.yml
  source/images/flags/de.svg
  source/localizable/header/_nav-primary.erb
  source/stylesheets/layout/_header.scss
Labels: ready, 🌐 all sites

#1934 Improve CAPP Quizzes page
  data/news_nl.yml
  data/redirects_nl.yml
  locales/nl.yml
  source/localizable/capp-quizzes.html.erb
  source/stylesheets/pages/_capp-quizzes.scss
Labels: ready, 🇳🇱 defacto.nl

#1935 ABC the NL locale file
  locales/nl.yml
Labels: ready, 🇳🇱 defacto.nl

#1936 ABC the DE locale file
  locales/de.yml
Labels: ready, 🇩🇪 defactolearning.de

#1937 ABC the EN locale file
  locales/en.yml
Labels: ready, 🇬🇧 en.defacto.nl

#1938 Update navigations
  locales/de.yml
  locales/en.yml
  locales/nl.yml
  source/layouts/layout.erb
  source/layouts/questionnaire.erb
  source/localizable/footer/_footer-nav.de.erb
  source/localizable/footer/_footer-nav.en.erb
  source/localizable/footer/_footer-nav.nl.erb
  source/localizable/header/_nav-primary.erb
  source/partials/footer/_footer-nav.de.erb
  source/partials/footer/_footer-nav.en.erb
  source/partials/footer/_footer-nav.nl.erb
  source/partials/footer/_footer.erb
  source/partials/footer/_small-footer.erb
  source/partials/header/_header.erb
  source/partials/header/_nav-dropdowns.erb
  source/partials/header/_nav-mobile.erb
  source/partials/header/_nav-primary.erb
Labels: ready, 🇳🇱 defacto.nl

#1943 Add CAPP Agile Learning productsheet PDF
  source/pdf/Productsheet-CAPP-Agile-Learning.pdf
Labels: ready, 🇳🇱 defacto.nl

#1942 Update 'Zukunft Personal' dates and introduction
  source/localizable/evenementen/_events.de.md.erb
Labels: ready, 🇩🇪 defactolearning.de

#1948 Remove some team members from the site
  data/team.yml
  source/images/team/albert-dijkslag.jpg
  source/images/team/laura-piel.jpg
  source/images/team/lennart-de-vries.jpg
Labels: ready, 🌐 all sites

#1886 Fix dropdown issue in IE11
  source/stylesheets/layout/_header.scss
Labels: ready, 🌐 all sites

#1940 Update CAPP Agile Learning product page to 2019
  data/downloads.yml
  locales/nl.yml
  source/images/gifs/wat-is-agile-learning.gif
  source/images/icons/capp-agile-learning-new.svg
  source/images/logos/new/logo-capp-agile-learning.svg
  source/images/moods/capp-agile-learning-new.jpg
  source/images/screenshots/capp-agile-dashboard.png
  source/images/screenshots/capp-agile-demo_nl.png
  source/images/screenshots/capp-agile-hero_nl.png
  source/images/screenshots/capp-agile-on-demand.png
  source/layouts/product_layout.erb
  source/localizable/capp-agile-learning.html.erb
  source/localizable/capp-agile-learning/_clients.nl.erb
  source/localizable/capp-agile-learning/_testimonials.erb
  source/localizable/capp-agile-learning/new/_introduction.nl.erb
  source/localizable/capp-agile-learning/new/_product-overview.nl.erb
  source/localizable/capp-agile-learning/old/_clients.de.erb
  source/localizable/capp-agile-learning/old/_clients.en.erb
  source/localizable/capp-agile-learning/old/_content.de.erb
  source/localizable/capp-agile-learning/old/_content.en.erb
  source/localizable/capp-agile-learning/old/_content.nl.erb
  source/localizable/capp-agile-learning/old/_hero.erb
  source/localizable/capp-agile-learning/old/_why.erb
  source/localizable/home/_solutions.erb
  source/localizable/producten/_producten.nl.md.erb
  source/localizable/themas/_70-20-10.nl.md.erb
  source/partials/_hero.erb
  source/partials/_on-page-navigation.erb
  source/partials/header/_nav-dropdowns.erb
  source/partials/header/_nav-mobile.erb
  source/pdf/Productsheet-CAPP-Agile-Learning.pdf
  source/stylesheets/base/_buttons.scss
  source/stylesheets/components/_hero.scss
  source/stylesheets/components/_on-page-navigation.scss
  source/stylesheets/config/_variables.scss
  source/stylesheets/layout/_header.scss
  source/stylesheets/pages/_capp-agile-learning.scss
  source/stylesheets/pages/_product.scss
  source/stylesheets/pages/_producten.scss
Labels: ready, 🇳🇱 defacto.nl

#1953 Add CAPP Agile Learning productsheet again
  source/pdf/Productsheet-CAPP-Agile-Learning.pdf
Labels: ready

#1955 Add updated My List pdf
  source/pdf/Infosheet_Mijn_lijst.pdf
Labels: ready, 🇳🇱 defacto.nl

#1954 Add new blog about curation
  source/blog/nl/2019-07-12-curation-mijn-lijst-persoonlijke-ontwikkeling-capp-lms.html.markdown
  source/images/blog/bastiaan.jpg
  source/images/blog/featured/20190715-curation.png
  source/images/blog/hugo.jpg
  source/images/blog/social/curation-1200x630.jpg
  source/stylesheets/posts/_posts.scss
Labels: ready, 🇳🇱 defacto.nl

#1956 Improve CAPP Agile Learning page
  source/localizable/capp-agile-learning.html.erb
  source/localizable/capp-agile-learning/_testimonials.erb
  source/localizable/capp-agile-learning/new/_download-productsheet.nl.erb
  source/localizable/capp-agile-learning/new/_introduction.nl.erb
  source/localizable/capp-agile-learning/new/_product-overview.nl.erb
  source/localizable/capp-agile-learning/old/_info-request.erb
  source/stylesheets/config/_variables.scss
  source/stylesheets/pages/_product-page.scss
  source/stylesheets/sections/_testimonials.scss
Labels: ready, 🇳🇱 defacto.nl

#1959 Update workshop post
  source/blog/nl/2017-02-22-met-e-learning-toekomst-vormgeven.html.markdown
Labels: ready, 🇳🇱 defacto.nl

#1958 Add blog about customer experiences
  source/blog/nl/2019-07-19-klanten-over-capp-lms.html.markdown
  source/images/blog/WZA-tweet.jpg
  source/images/blog/featured/20190717-capp-lms-taart.jpg
  source/images/blog/social/capp-lms-ervaringen-1200x630.jpg
  source/images/moods/capp-lms-dashboard.jpg
Labels: ready, 🇳🇱 defacto.nl

#1962 Remove some references
  data/clients.yml
  data/clients_de.yml
  source/images/references/dpa-benkis.png
  source/images/references/kaldi.png
  source/images/references/kvk.png
  source/images/references/stmr.png
  source/images/references/zuidzorg.png
Labels: ready, 🌐 all sites

#1950 Minor styling fixes
  source/stylesheets/components/_code.scss.erb
  source/stylesheets/config/_variables.scss
  source/stylesheets/pages/_bedankt.scss
  source/stylesheets/pages/_capp-quizzes.scss
Labels: ready, 🌐 all sites

#1963 Update new Agile Learning product page
  source/localizable/capp-agile-learning/new/_product-overview.nl.erb
Labels: ready, 🇳🇱 defacto.nl

#1944 Generate navigations from data yamls
  data/navigations_de.yml
  data/navigations_en.yml
  data/navigations_nl.yml
  helpers/navigation.rb
  locales/de.yml
  locales/en.yml
  locales/nl.yml
  source/partials/footer/_footer-nav.de.erb
  source/partials/footer/_footer-nav.en.erb
  source/partials/footer/_footer-nav.nl.erb
  source/partials/footer/_footer-navigation.erb
  source/partials/footer/_footer.erb
  source/partials/header/_nav-dropdowns.erb
  source/partials/header/_nav-mobile.erb
  source/partials/header/_nav-primary.erb
  source/stylesheets/layout/_header.scss
Labels: ready, 🌐 all sites

#1964 Use new CAPP Agile Learning icon in navigation
  data/navigations_nl.yml
Labels: ready, 🇳🇱 defacto.nl

#1968 Update german case links
  source/cases/de/evangelisches-krankenhaus-oldenburg.html.markdown
  source/cases/de/fek-neumunster.html.markdown
  source/cases/de/mumc.html.markdown
  source/cases/de/pohl-boskamp.html.markdown
  source/cases/de/strukton.html.markdown
  source/cases/de/zinn.html.markdown
Labels: ready, 🇩🇪 defactolearning.de

#1967 Update introduction section padding
  source/stylesheets/pages/_product-page.scss
Labels: ready, 🇳🇱 defacto.nl

#1970 Improve product icons on white
  data/navigations_nl.yml
  source/images/icons/capp-agile-learning-new.svg
  source/images/icons/capp-compliance-new.svg
  source/images/icons/capp-lms-new.svg
  source/localizable/home/_solutions.erb
Labels: proof of concept, 🇳🇱 defacto.nl

#1969 Improve CAPP Compliance product page
  source/localizable/capp-compliance/nl/_product-overview.erb
Labels: ready, 🇳🇱 defacto.nl
